--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.ActionEase : cc.ActionInterval
local m = {}

--- brief Initializes the action.<br>
--- return Return true when the initialization success, otherwise return false.
---@param action cc.ActionInterval
---@return boolean
function m:initWithAction(action) end

--- brief Get the pointer of the inner action.<br>
--- return The pointer of the inner action.
---@return cc.ActionInterval
function m:getInnerAction() end

--- 
---@param target cc.Node
---@return cc.ActionEase
function m:startWithTarget(target) end

--- 
---@return cc.ActionEase
function m:stop() end

--- 
---@param time float
---@return cc.ActionEase
function m:update(time) end



return m