--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class ccs.ActionScaleFrame : ccs.ActionFrame
local m = {}

--- Changes the scale action scaleY.<br>
--- param rotation the scale action scaleY.
---@param scaleY float
---@return ccs.ActionScaleFrame
function m:setScaleY(scaleY) end

--- Changes the scale action scaleX.<br>
--- param the scale action scaleX.
---@param scaleX float
---@return ccs.ActionScaleFrame
function m:setScaleX(scaleX) end

--- Gets the scale action scaleY.<br>
--- return the scale action scaleY.
---@return float
function m:getScaleY() end

--- Gets the scale action scaleX.<br>
--- return the scale action scaleX.
---@return float
function m:getScaleX() end

--- Gets the ActionInterval of ActionFrame.<br>
--- param duration   the duration time of ActionFrame<br>
--- return ActionInterval
---@param duration float
---@return cc.ActionInterval
function m:getAction(duration) end

--- Default constructor
---@return ccs.ActionScaleFrame
function m:ActionScaleFrame() end



return m