--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class ccs.ActionTimelineCache
local m = {}

---  Clone a action with the specified name from the container. 
---@param fileName string
---@return ccs.ActionTimeline
function m:createActionFromJson(fileName) end

--- 
---@param fileName string
---@return ccs.ActionTimeline
function m:createActionWithFlatBuffersFile(fileName) end

--- 
---@param fileName string
---@return ccs.ActionTimeline
function m:loadAnimationActionWithFlatBuffersFile(fileName) end

--- 
---@param fileName string
---@param content string
---@return ccs.ActionTimeline
function m:createActionFromContent(fileName, content) end

--- 
---@return ccs.ActionTimelineCache
function m:purge() end

--- 
---@return ccs.ActionTimelineCache
function m:init() end

--- 
---@param fileName string
---@param content string
---@return ccs.ActionTimeline
function m:loadAnimationActionWithContent(fileName, content) end

--- 
---@param fileName string
---@return ccs.ActionTimeline
function m:loadAnimationActionWithFile(fileName) end

---  Remove action with filename, and also remove other resource relate with this file 
---@param fileName string
---@return ccs.ActionTimelineCache
function m:removeAction(fileName) end

--- 
---@param fileName string
---@return ccs.ActionTimeline
function m:createActionWithFlatBuffersForSimulator(fileName) end

---  Destroys the singleton 
---@return ccs.ActionTimelineCache
function m:destroyInstance() end

--- 
---@param fileName string
---@return ccs.ActionTimeline
function m:createAction(fileName) end



return m