--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class ccs.ActionManagerEx : ccs.Ref
local m = {}

--- Stop an Action with a name.<br>
--- param jsonName  UI file name<br>
--- param actionName  action name in the UIfile.<br>
--- return  ActionObject which named as the param name
---@param jsonName char
---@param actionName char
---@return ccs.ActionObject
function m:stopActionByName(jsonName, actionName) end

--- Gets an ActionObject with a name.<br>
--- param jsonName  UI file name<br>
--- param actionName  action name in the UI file.<br>
--- return  ActionObject which named as the param name
---@param jsonName char
---@param actionName char
---@return ccs.ActionObject
function m:getActionByName(jsonName, actionName) end

--- 
---@return int
function m:getStudioVersionNumber() end

---@overload fun(self:ccs.ActionManagerEx, jsonName:char, actionName:char):ccs.ActionObject
---@param jsonName char
---@param actionName char
---@param func cc.CallFunc
---@return ccs.ActionObject
function m:playActionByName(jsonName, actionName, func) end

--- Release all actions.
---@return ccs.ActionManagerEx
function m:releaseActions() end

--- Purges ActionManager point.<br>
--- js purge<br>
--- lua destroyActionManager
---@return ccs.ActionManagerEx
function m:destroyInstance() end

--- Gets the static instance of ActionManager.<br>
--- js getInstance<br>
--- lua getInstance
---@return ccs.ActionManagerEx
function m:getInstance() end



return m