--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class ccs.AlphaFrame : ccs.Frame
local m = {}

--- 
---@return uchar
function m:getAlpha() end

--- 
---@param alpha uchar
---@return ccs.AlphaFrame
function m:setAlpha(alpha) end

--- 
---@return ccs.AlphaFrame
function m:create() end

--- 
---@return ccs.Frame
function m:clone() end

--- 
---@return ccs.AlphaFrame
function m:AlphaFrame() end



return m