--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.AmbientLight : cc.BaseLight
local m = {}

--- Creates a ambient light.<br>
--- param color The light's color.<br>
--- return The new ambient light.
---@param color cc.c3b
---@return cc.AmbientLight
function m:create(color) end

--- 
---@return int
function m:getLightType() end

--- 
---@return cc.AmbientLight
function m:AmbientLight() end



return m