--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.Animate : cc.ActionInterval
local m = {}

---  initializes the action with an Animation and will restore the original frame when the animation is over 
---@param animation cc.Animation
---@return boolean
function m:initWithAnimation(animation) end

---@return cc.Animation
function m:getAnimation() end

--- Gets the index of sprite frame currently displayed.<br>
--- return int  the index of sprite frame currently displayed.
---@return int
function m:getCurrentFrameIndex() end

---  Sets the Animation object to be animated <br>
--- param animation certain animation.
---@param animation cc.Animation
---@return cc.Animate
function m:setAnimation(animation) end

---  Creates the action with an Animation and will restore the original frame when the animation is over.<br>
--- param animation A certain animation.<br>
--- return An autoreleased Animate object.
---@param animation cc.Animation
---@return cc.Animate
function m:create(animation) end

--- 
---@param target cc.Node
---@return cc.Animate
function m:startWithTarget(target) end

--- 
---@return cc.Animate
function m:clone() end

--- 
---@return cc.Animate
function m:stop() end

--- 
---@return cc.Animate
function m:reverse() end

--- param t In seconds.
---@param t float
---@return cc.Animate
function m:update(t) end

--- 
---@return cc.Animate
function m:Animate() end



return m