--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.Animate3D : cc.ActionInterval
local m = {}

--- 
---@param keyFrame int
---@param userInfo table<any:any>
---@return cc.Animate3D
function m:setKeyFrameUserInfo(keyFrame, userInfo) end

--- get & set speed, negative speed means playing reverse 
---@return float
function m:getSpeed() end

--- set animate quality
---@param quality int
---@return cc.Animate3D
function m:setQuality(quality) end

--- 
---@param weight float
---@return cc.Animate3D
function m:setWeight(weight) end

--- 
---@return cc.Animate3D
function m:removeFromMap() end

--- 
---@param animation cc.Animation3D
---@param startFrame int
---@param endFrame int
---@param frameRate float
---@return boolean
function m:initWithFrames(animation, startFrame, endFrame, frameRate) end

--- 
---@return float
function m:getOriginInterval() end

--- 
---@param speed float
---@return cc.Animate3D
function m:setSpeed(speed) end

---@overload fun(self:cc.Animate3D, animation:cc.Animation3D):boolean
---@param animation cc.Animation3D
---@param fromTime float
---@param duration float
---@return boolean
function m:init(animation, fromTime, duration) end

--- get & set origin interval
---@param interval float
---@return cc.Animate3D
function m:setOriginInterval(interval) end

--- get & set blend weight, weight must positive
---@return float
function m:getWeight() end

--- get animate quality
---@return int
function m:getQuality() end

---@overload fun(self:cc.Animate3D, animation:cc.Animation3D):cc.Animate3D
---@param animation cc.Animation3D
---@param fromTime float
---@param duration float
---@return cc.Animate3D
function m:create(animation, fromTime, duration) end

---  get animate transition time between 3d animations 
---@return float
function m:getTransitionTime() end

--- create Animate3D by frame section, [startFrame, endFrame)<br>
--- param animation used to generate animate3D<br>
--- param startFrame<br>
--- param endFrame<br>
--- param frameRate default is 30 per second<br>
--- return Animate3D created using animate
---@param animation cc.Animation3D
---@param startFrame int
---@param endFrame int
---@param frameRate float
---@return cc.Animate3D
function m:createWithFrames(animation, startFrame, endFrame, frameRate) end

---  set animate transition time between 3d animations 
---@param transTime float
---@return cc.Animate3D
function m:setTransitionTime(transTime) end

--- 
---@param target cc.Node
---@return cc.Animate3D
function m:startWithTarget(target) end

--- 
---@return cc.Animate3D
function m:reverse() end

--- 
---@return cc.Animate3D
function m:clone() end

--- 
---@return cc.Animate3D
function m:stop() end

--- 
---@param t float
---@return cc.Animate3D
function m:update(t) end

--- 
---@param dt float
---@return cc.Animate3D
function m:step(dt) end

--- 
---@return cc.Animate3D
function m:Animate3D() end



return m