--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class ccs.ArmatureDisplayData : ccs.DisplayData
local m = {}

--- 
---@return ccs.ArmatureDisplayData
function m:create() end

--- js ctor
---@return ccs.ArmatureDisplayData
function m:ArmatureDisplayData() end



return m