--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class ccs.ArmatureData : ccs.Ref
local m = {}

--- 
---@param boneData ccs.BoneData
---@return ccs.ArmatureData
function m:addBoneData(boneData) end

--- 
---@return boolean
function m:init() end

--- 
---@param boneName string
---@return ccs.BoneData
function m:getBoneData(boneName) end

--- 
---@return ccs.ArmatureData
function m:create() end

--- js ctor
---@return ccs.ArmatureData
function m:ArmatureData() end



return m