--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.AttachNode : cc.Node
local m = {}

--- creates an AttachNode<br>
--- param attachBone The bone to which the AttachNode is going to attach, the attacheBone must be a bone of the AttachNode's parent
---@param attachBone cc.Bone3D
---@return cc.AttachNode
function m:create(attachBone) end

--- 
---@param renderer cc.Renderer
---@param parentTransform mat4_table
---@param parentFlags uint
---@return cc.AttachNode
function m:visit(renderer, parentTransform, parentFlags) end

--- 
---@return mat4_table
function m:getWorldToNodeTransform() end

--- 
---@return mat4_table
function m:getNodeToWorldTransform() end

--- 
---@return mat4_table
function m:getNodeToParentTransform() end

--- 
---@return cc.AttachNode
function m:AttachNode() end



return m