--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class ccs.BaseData : ccs.Ref
local m = {}

--- 
---@return cc.c4b
function m:getColor() end

--- 
---@param color cc.c4b
---@return ccs.BaseData
function m:setColor(color) end

--- 
---@return ccs.BaseData
function m:create() end

--- js ctor
---@return ccs.BaseData
function m:BaseData() end



return m