--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class ccs.BatchNode : ccs.Node
local m = {}

--- 
---@return ccs.BatchNode
function m:create() end

---@overload fun(self:ccs.BatchNode, pChild:cc.Node, zOrder:int, tag:string):ccs.BatchNode
---@param pChild cc.Node
---@param zOrder int
---@param tag int
---@return ccs.BatchNode
function m:addChild(pChild, zOrder, tag) end

--- js NA
---@return boolean
function m:init() end

--- 
---@param renderer cc.Renderer
---@param transform mat4_table
---@param flags uint
---@return ccs.BatchNode
function m:draw(renderer, transform, flags) end

--- 
---@param child cc.Node
---@param cleanup boolean
---@return ccs.BatchNode
function m:removeChild(child, cleanup) end



return m