--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.BezierTo : cc.BezierBy
local m = {}

--- param t In seconds.
---@param t float
---@param c cc._ccBezierConfig
---@return boolean
function m:initWithDuration(t, c) end

--- 
---@param target cc.Node
---@return cc.BezierTo
function m:startWithTarget(target) end

--- 
---@return cc.BezierTo
function m:clone() end

--- 
---@return cc.BezierTo
function m:reverse() end

--- 
---@return cc.BezierTo
function m:BezierTo() end



return m