--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.BillBoard : cc.Sprite
local m = {}

---  Get the billboard rotation mode. 
---@return int
function m:getMode() end

---  Set the billboard rotation mode. 
---@param mode int
---@return cc.BillBoard
function m:setMode(mode) end

---@overload fun(self:cc.BillBoard, filename:string, rect:int):cc.BillBoard
---@overload fun(self:cc.BillBoard, filename:int):cc.BillBoard
---@param filename string
---@param rect cc.rect
---@param mode int
---@return cc.BillBoard
function m:create(filename, rect, mode) end

--- Creates a BillBoard with a Texture2D object.<br>
--- After creation, the rect will be the size of the texture, and the offset will be (0,0).<br>
--- param   texture    A pointer to a Texture2D object.<br>
--- return  An autoreleased BillBoard object
---@param texture cc.Texture2D
---@param mode int
---@return cc.BillBoard
function m:createWithTexture(texture, mode) end

---  update billboard's transform and turn it towards camera 
---@param renderer cc.Renderer
---@param parentTransform mat4_table
---@param parentFlags uint
---@return cc.BillBoard
function m:visit(renderer, parentTransform, parentFlags) end

--- 
---@return cc.BillBoard
function m:BillBoard() end



return m