--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.CameraBackgroundDepthBrush : cc.CameraBackgroundBrush
local m = {}

--- Set depth<br>
--- param depth Depth used to clear depth buffer
---@param depth float
---@return cc.CameraBackgroundDepthBrush
function m:setDepth(depth) end

--- Create a depth brush<br>
--- param depth Depth used to clear the depth buffer<br>
--- return Created brush
---@param depth float
---@return cc.CameraBackgroundDepthBrush
function m:create(depth) end

--- Get brush type. Should be BrushType::DEPTH<br>
--- return brush type
---@return int
function m:getBrushType() end

--- Draw background
---@param camera cc.Camera
---@return cc.CameraBackgroundDepthBrush
function m:drawBackground(camera) end

--- 
---@return boolean
function m:init() end

--- 
---@return cc.CameraBackgroundDepthBrush
function m:CameraBackgroundDepthBrush() end



return m