--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.CameraBackgroundColorBrush : cc.CameraBackgroundDepthBrush
local m = {}

--- Set clear color<br>
--- param color Color used to clear the color buffer
---@param color cc.c4f
---@return cc.CameraBackgroundColorBrush
function m:setColor(color) end

--- Create a color brush<br>
--- param color Color used to clear the color buffer<br>
--- param depth Depth used to clear the depth buffer<br>
--- return Created brush
---@param color cc.c4f
---@param depth float
---@return cc.CameraBackgroundColorBrush
function m:create(color, depth) end

--- Get brush type. Should be BrushType::COLOR<br>
--- return brush type
---@return int
function m:getBrushType() end

--- 
---@return boolean
function m:init() end

--- 
---@return cc.CameraBackgroundColorBrush
function m:CameraBackgroundColorBrush() end



return m