--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.CardinalSplineTo : cc.ActionInterval
local m = {}

---  Return a PointArray.<br>
--- return A PointArray.
---@return point_table
function m:getPoints() end

---  It will update the target position and change the _previousPosition to newPos<br>
--- param newPos The new position.
---@param newPos cc.vec2
---@return cc.CardinalSplineTo
function m:updatePosition(newPos) end

--- Initializes the action with a duration and an array of points.<br>
--- param duration In seconds.<br>
--- param points An PointArray.<br>
--- param tension Goodness of fit.
---@param duration float
---@param points point_table
---@param tension float
---@return boolean
function m:initWithDuration(duration, points, tension) end

--- 
---@param target cc.Node
---@return cc.CardinalSplineTo
function m:startWithTarget(target) end

--- 
---@return cc.CardinalSplineTo
function m:clone() end

--- 
---@return cc.CardinalSplineTo
function m:reverse() end

--- param time In seconds.
---@param time float
---@return cc.CardinalSplineTo
function m:update(time) end

--- js ctor<br>
--- lua NA
---@return cc.CardinalSplineTo
function m:CardinalSplineTo() end



return m