--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.CardinalSplineBy : cc.CardinalSplineTo
local m = {}

--- 
---@param target cc.Node
---@return cc.CardinalSplineBy
function m:startWithTarget(target) end

--- 
---@return cc.CardinalSplineBy
function m:clone() end

--- 
---@param newPos cc.vec2
---@return cc.CardinalSplineBy
function m:updatePosition(newPos) end

--- 
---@return cc.CardinalSplineBy
function m:reverse() end

--- 
---@return cc.CardinalSplineBy
function m:CardinalSplineBy() end



return m