--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class ccui.CheckBox : ccui.AbstractCheckButton
local m = {}

--- Add a callback function which would be called when checkbox is selected or unselected.<br>
---@param callback fun
---@return ccui.CheckBox
function m:addEventListener(callback) end

---@overload fun(self:ccui.CheckBox):ccui.CheckBox
---@overload fun(self:ccui.CheckBox, backGround:string, backGroundSelected:string, cross:int):ccui.CheckBox
---@param backGround string
---@param backGroundSelected string
---@param cross string
---@param backGroundDisabled string
---@param frontCrossDisabled string
---@param texType int
---@return ccui.CheckBox
function m:create(backGround, backGroundSelected, cross, backGroundDisabled, frontCrossDisabled, texType) end

--- 
---@return cc.Ref
function m:createInstance() end

--- 
---@return string
function m:getDescription() end

--- Default constructor.<br>
--- lua new
---@return ccui.CheckBox
function m:CheckBox() end



return m