--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.ClippingRectangleNode : cc.Node
local m = {}

--- brief Get whether the clipping is enabled or not.<br>
--- return Whether the clipping is enabled or not. Default is true.
---@return boolean
function m:isClippingEnabled() end

--- brief Enable/Disable the clipping.<br>
--- param enabled Pass true to enable clipping. Pass false to disable clipping.
---@param enabled boolean
---@return cc.ClippingRectangleNode
function m:setClippingEnabled(enabled) end

--- brief Get the clipping rectangle.<br>
--- return The clipping rectangle.
---@return cc.rect
function m:getClippingRegion() end

--- brief Set the clipping rectangle.<br>
--- param clippingRegion Specify the clipping rectangle.
---@param clippingRegion cc.rect
---@return cc.ClippingRectangleNode
function m:setClippingRegion(clippingRegion) end

---@overload fun(self:cc.ClippingRectangleNode):cc.ClippingRectangleNode
---@param clippingRegion cc.rect
---@return cc.ClippingRectangleNode
function m:create(clippingRegion) end

--- 
---@param renderer cc.Renderer
---@param parentTransform mat4_table
---@param parentFlags uint
---@return cc.ClippingRectangleNode
function m:visit(renderer, parentTransform, parentFlags) end



return m