--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class ccs.ComController : ccs.Component,ccs.InputDelegate
local m = {}

--- 
---@return ccs.ComController
function m:create() end

--- 
---@return cc.Ref
function m:createInstance() end

--- js NA<br>
--- lua NA
---@return ccs.ComController
function m:onRemove() end

--- 
---@param delta float
---@return ccs.ComController
function m:update(delta) end

--- 
---@return boolean
function m:init() end

--- js NA<br>
--- lua NA
---@return ccs.ComController
function m:onAdd() end

--- js ctor
---@return ccs.ComController
function m:ComController() end



return m