--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.ComponentLua : cc.Component
local m = {}

--- This function is used to be invoked from lua side to get the corresponding script object of this component.
---@return void
function m:getScriptObject() end

--- 
---@param dt float
---@return cc.ComponentLua
function m:update(dt) end

--- 
---@param scriptFileName string
---@return cc.ComponentLua
function m:create(scriptFileName) end

--- 
---@param scriptFileName string
---@return cc.ComponentLua
function m:ComponentLua(scriptFileName) end



return m