--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class ccs.ComRender : ccs.Component
local m = {}

--- 
---@param node cc.Node
---@return ccs.ComRender
function m:setNode(node) end

--- 
---@return cc.Node
function m:getNode() end

---@overload fun(self:ccs.ComRender):ccs.ComRender
---@param node cc.Node
---@param comName char
---@return ccs.ComRender
function m:create(node, comName) end

--- 
---@return cc.Ref
function m:createInstance() end

--- 
---@param r void
---@return boolean
function m:serialize(r) end

--- js NA<br>
--- lua NA
---@return ccs.ComRender
function m:onRemove() end

--- js NA<br>
--- lua NA
---@return ccs.ComRender
function m:onAdd() end



return m