--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.Console : cc.Ref
local m = {}

---@overload fun(self:cc.Console, cmdName:cc.Console::Command, subCmd:cc.Console::Command):cc.Console
---@param cmdName string
---@param subCmd cc.Console::Command
---@return cc.Console
function m:addSubCommand(cmdName, subCmd) end

---  starts listening to specified TCP port 
---@param port int
---@return boolean
function m:listenOnTCP(port) end

---  log something in the console 
---@param buf char
---@return cc.Console
function m:log(buf) end

---@overload fun(self:cc.Console, cmdName:cc.Console::Command, subCmdName:string):cc.Console::Command
---@param cmdName string
---@param subCmdName string
---@return cc.Console::Command
function m:getSubCommand(cmdName, subCmdName) end

---  delete custom command 
---@param cmdName string
---@return cc.Console
function m:delCommand(cmdName) end

---  stops the Console. 'stop' will be called at destruction time as well 
---@return cc.Console
function m:stop() end

---  get custom command 
---@param cmdName string
---@return cc.Console::Command
function m:getCommand(cmdName) end

---  starts listening to specified file descriptor 
---@param fd int
---@return boolean
function m:listenOnFileDescriptor(fd) end

--- set bind address<br>
--- address : 127.0.0.1
---@param address string
---@return cc.Console
function m:setBindAddress(address) end

---@overload fun(self:cc.Console, cmdName:cc.Console::Command, subCmdName:string):cc.Console
---@param cmdName string
---@param subCmdName string
---@return cc.Console
function m:delSubCommand(cmdName, subCmdName) end

---  Checks whether the server for console is bound with ipv6 address 
---@return boolean
function m:isIpv6Server() end



return m