--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.ControlHuePicker : cc.Control
local m = {}

--- 
---@param target cc.Node
---@param pos cc.vec2
---@return boolean
function m:initWithTargetAndPos(target, pos) end

--- 
---@param val float
---@return cc.ControlHuePicker
function m:setHue(val) end

--- 
---@return cc.vec2
function m:getStartPos() end

--- 
---@return float
function m:getHue() end

--- 
---@return cc.Sprite
function m:getSlider() end

--- 
---@param var cc.Sprite
---@return cc.ControlHuePicker
function m:setBackground(var) end

--- 
---@param val float
---@return cc.ControlHuePicker
function m:setHuePercentage(val) end

--- 
---@return cc.Sprite
function m:getBackground() end

--- 
---@return float
function m:getHuePercentage() end

--- 
---@param var cc.Sprite
---@return cc.ControlHuePicker
function m:setSlider(var) end

--- 
---@param target cc.Node
---@param pos cc.vec2
---@return cc.ControlHuePicker
function m:create(target, pos) end

--- 
---@param enabled boolean
---@return cc.ControlHuePicker
function m:setEnabled(enabled) end

--- 
---@param pTouch cc.Touch
---@param pEvent cc.Event
---@return cc.ControlHuePicker
function m:onTouchMoved(pTouch, pEvent) end

--- 
---@param touch cc.Touch
---@param pEvent cc.Event
---@return boolean
function m:onTouchBegan(touch, pEvent) end

--- js ctor
---@return cc.ControlHuePicker
function m:ControlHuePicker() end



return m