--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class ccs.ContourData : ccs.Ref
local m = {}

--- 
---@return boolean
function m:init() end

--- 
---@param vertex cc.vec2
---@return ccs.ContourData
function m:addVertex(vertex) end

--- 
---@return ccs.ContourData
function m:create() end

--- js ctor
---@return ccs.ContourData
function m:ContourData() end



return m