--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.ControlColourPicker : cc.Control
local m = {}

--- 
---@param sender cc.Ref
---@param controlEvent int
---@return cc.ControlColourPicker
function m:hueSliderValueChanged(sender, controlEvent) end

--- 
---@return cc.ControlHuePicker
function m:getHuePicker() end

--- 
---@return cc.ControlSaturationBrightnessPicker
function m:getcolourPicker() end

--- 
---@param var cc.Sprite
---@return cc.ControlColourPicker
function m:setBackground(var) end

--- 
---@param var cc.ControlSaturationBrightnessPicker
---@return cc.ControlColourPicker
function m:setcolourPicker(var) end

--- 
---@param sender cc.Ref
---@param controlEvent int
---@return cc.ControlColourPicker
function m:colourSliderValueChanged(sender, controlEvent) end

--- 
---@param var cc.ControlHuePicker
---@return cc.ControlColourPicker
function m:setHuePicker(var) end

--- 
---@return cc.Sprite
function m:getBackground() end

--- 
---@return cc.ControlColourPicker
function m:create() end

--- 
---@param bEnabled boolean
---@return cc.ControlColourPicker
function m:setEnabled(bEnabled) end

--- 
---@return boolean
function m:init() end

--- 
---@param colorValue cc.c3b
---@return cc.ControlColourPicker
function m:setColor(colorValue) end

--- js ctor<br>
--- lua new
---@return cc.ControlColourPicker
function m:ControlColourPicker() end



return m