--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.DirectionLight : cc.BaseLight
local m = {}

--- Returns the Direction in parent.
---@return cc.vec3
function m:getDirection() end

--- Returns direction in world.
---@return cc.vec3
function m:getDirectionInWorld() end

--- Sets the Direction in parent.<br>
--- param dir The Direction in parent.
---@param dir cc.vec3
---@return cc.DirectionLight
function m:setDirection(dir) end

--- Creates a direction light.<br>
--- param direction The light's direction<br>
--- param color The light's color.<br>
--- return The new direction light.
---@param direction cc.vec3
---@param color cc.c3b
---@return cc.DirectionLight
function m:create(direction, color) end

--- 
---@return int
function m:getLightType() end

--- 
---@return cc.DirectionLight
function m:DirectionLight() end



return m