--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class ccs.DisplayData : ccs.Ref
local m = {}

--- 
---@param displayData ccs.DisplayData
---@return ccs.DisplayData
function m:copy(displayData) end

--- 
---@param displayName string
---@return string
function m:changeDisplayToTexture(displayName) end

--- 
---@return ccs.DisplayData
function m:create() end

--- js ctor
---@return ccs.DisplayData
function m:DisplayData() end



return m