--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.EaseIn : cc.EaseRateAction
local m = {}

--- 
---@param action cc.ActionInterval
---@param rate float
---@return cc.EaseIn
function m:create(action, rate) end

--- 
---@return cc.EaseIn
function m:clone() end

--- 
---@param time float
---@return cc.EaseIn
function m:update(time) end

--- 
---@return cc.EaseRateAction
function m:reverse() end

--- 
---@return cc.EaseIn
function m:EaseIn() end



return m