--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.EaseExponentialInOut : cc.ActionEase
local m = {}

--- 
---@param action cc.ActionInterval
---@return cc.EaseExponentialInOut
function m:create(action) end

--- 
---@return cc.EaseExponentialInOut
function m:clone() end

--- 
---@param time float
---@return cc.EaseExponentialInOut
function m:update(time) end

--- 
---@return cc.ActionEase
function m:reverse() end

--- 
---@return cc.EaseExponentialInOut
function m:EaseExponentialInOut() end



return m