--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.EaseCubicActionOut : cc.ActionEase
local m = {}

--- 
---@param action cc.ActionInterval
---@return cc.EaseCubicActionOut
function m:create(action) end

--- 
---@return cc.EaseCubicActionOut
function m:clone() end

--- 
---@param time float
---@return cc.EaseCubicActionOut
function m:update(time) end

--- 
---@return cc.ActionEase
function m:reverse() end

--- 
---@return cc.EaseCubicActionOut
function m:EaseCubicActionOut() end



return m