--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.EaseBezierAction : cc.ActionEase
local m = {}

--- brief Set the bezier parameters.
---@param p0 float
---@param p1 float
---@param p2 float
---@param p3 float
---@return cc.EaseBezierAction
function m:setBezierParamer(p0, p1, p2, p3) end

--- brief Create the action with the inner action.<br>
--- param action The pointer of the inner action.<br>
--- return A pointer of EaseBezierAction action. If creation failed, return nil.
---@param action cc.ActionInterval
---@return cc.EaseBezierAction
function m:create(action) end

--- 
---@return cc.EaseBezierAction
function m:clone() end

--- 
---@param time float
---@return cc.EaseBezierAction
function m:update(time) end

--- 
---@return cc.EaseBezierAction
function m:reverse() end

--- 
---@return cc.EaseBezierAction
function m:EaseBezierAction() end



return m