--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.EaseSineIn : cc.ActionEase
local m = {}

--- 
---@param action cc.ActionInterval
---@return cc.EaseSineIn
function m:create(action) end

--- 
---@return cc.EaseSineIn
function m:clone() end

--- 
---@param time float
---@return cc.EaseSineIn
function m:update(time) end

--- 
---@return cc.ActionEase
function m:reverse() end

--- 
---@return cc.EaseSineIn
function m:EaseSineIn() end



return m