--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.EventKeyboard : cc.Event
local m = {}

---  Constructor.<br>
--- param keyCode A given keycode.<br>
--- param isPressed True if the key is pressed.<br>
--- js ctor
---@param keyCode int
---@param isPressed boolean
---@return cc.EventKeyboard
function m:EventKeyboard(keyCode, isPressed) end



return m