--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.EventListenerCustom : cc.EventListener
local m = {}

--- 
---@return cc.EventListenerCustom
function m:clone() end

--- / Overrides
---@return boolean
function m:checkAvailable() end

---  Constructor 
---@return cc.EventListenerCustom
function m:EventListenerCustom() end



return m