--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.EventController : cc.Event
local m = {}

---  Gets the event type of the controller.<br>
--- return The event type of the controller.
---@return int
function m:getControllerEventType() end

---  Sets the connect status.<br>
--- param True if it's connected.
---@param isConnected boolean
---@return cc.EventController
function m:setConnectStatus(isConnected) end

---  Gets the connect status.<br>
--- return True if it's connected.
---@return boolean
function m:isConnected() end

--- 
---@param keyCode int
---@return cc.EventController
function m:setKeyCode(keyCode) end

--- 
---@return cc.Controller
function m:getController() end

---  Gets the key code of the controller.<br>
--- return The key code of the controller.
---@return int
function m:getKeyCode() end

---@overload fun(self:cc.EventController, type:int, controller:cc.Controller, keyCode:boolean):cc.EventController
---@param type int
---@param controller cc.Controller
---@param keyCode int
---@return cc.EventController
function m:EventController(type, controller, keyCode) end



return m