--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.EventListenerKeyboard : cc.EventListener
local m = {}

--- 
---@return boolean
function m:init() end

--- / Overrides
---@return cc.EventListenerKeyboard
function m:clone() end

--- 
---@return boolean
function m:checkAvailable() end

--- 
---@return cc.EventListenerKeyboard
function m:EventListenerKeyboard() end



return m