--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.EventMouse : cc.Event
local m = {}

---  Returns the previous touch location in screen coordinates.<br>
--- return The previous touch location in screen coordinates.<br>
--- js NA
---@return cc.vec2
function m:getPreviousLocationInView() end

---  Returns the current touch location in OpenGL coordinates.<br>
--- return The current touch location in OpenGL coordinates.
---@return cc.vec2
function m:getLocation() end

---  Get mouse button.<br>
--- return The mouse button.<br>
--- js getButton
---@return int
function m:getMouseButton() end

---  Returns the previous touch location in OpenGL coordinates.<br>
--- return The previous touch location in OpenGL coordinates.<br>
--- js NA
---@return cc.vec2
function m:getPreviousLocation() end

---  Returns the delta of 2 current touches locations in screen coordinates.<br>
--- return The delta of 2 current touches locations in screen coordinates.
---@return cc.vec2
function m:getDelta() end

---  Set mouse scroll data.<br>
--- param scrollX The scroll data of x axis.<br>
--- param scrollY The scroll data of y axis.
---@param scrollX float
---@param scrollY float
---@return cc.EventMouse
function m:setScrollData(scrollX, scrollY) end

---  Returns the start touch location in screen coordinates.<br>
--- return The start touch location in screen coordinates.<br>
--- js NA
---@return cc.vec2
function m:getStartLocationInView() end

---  Returns the start touch location in OpenGL coordinates.<br>
--- return The start touch location in OpenGL coordinates.<br>
--- js NA
---@return cc.vec2
function m:getStartLocation() end

---  Set mouse button.<br>
--- param button a given mouse button.<br>
--- js setButton
---@param button int
---@return cc.EventMouse
function m:setMouseButton(button) end

---  Returns the current touch location in screen coordinates.<br>
--- return The current touch location in screen coordinates.
---@return cc.vec2
function m:getLocationInView() end

---  Get mouse scroll data of y axis.<br>
--- return The scroll data of y axis.
---@return float
function m:getScrollY() end

---  Get mouse scroll data of x axis.<br>
--- return The scroll data of x axis.
---@return float
function m:getScrollX() end

---  Get the cursor position of x axis.<br>
--- return The x coordinate of cursor position.<br>
--- js getLocationX
---@return float
function m:getCursorX() end

---  Get the cursor position of y axis.<br>
--- return The y coordinate of cursor position.<br>
--- js getLocationY
---@return float
function m:getCursorY() end

---  Set the cursor position.<br>
--- param x The x coordinate of cursor position.<br>
--- param y The y coordinate of cursor position.<br>
--- js setLocation
---@param x float
---@param y float
---@return cc.EventMouse
function m:setCursorPosition(x, y) end

---  Constructor.<br>
--- param mouseEventCode A given mouse event type.<br>
--- js ctor
---@param mouseEventCode int
---@return cc.EventMouse
function m:EventMouse(mouseEventCode) end



return m