--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.EventTouch : cc.Event
local m = {}

---  Get event code.<br>
--- return The code of the event.
---@return int
function m:getEventCode() end

---  Set the event code.<br>
--- param eventCode A given EventCode.
---@param eventCode int
---@return cc.EventTouch
function m:setEventCode(eventCode) end

--- Constructor.<br>
--- js NA
---@return cc.EventTouch
function m:EventTouch() end



return m