--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.EventFocus : cc.Event
local m = {}

---  Constructor.<br>
--- param widgetLoseFocus The widget which lose focus.<br>
--- param widgetGetFocus The widget which get focus.<br>
--- js ctor
---@param widgetLoseFocus ccui.Widget
---@param widgetGetFocus ccui.Widget
---@return cc.EventFocus
function m:EventFocus(widgetLoseFocus, widgetGetFocus) end



return m