--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.EventListenerPhysicsContact : cc.EventListenerCustom
local m = {}

---  Create the listener. 
---@return cc.EventListenerPhysicsContact
function m:create() end

---  Clone an object from this listener.
---@return cc.EventListenerPhysicsContact
function m:clone() end

---  Check the listener is available.<br>
--- return True if there's one available callback function at least, false if there's no one.
---@return boolean
function m:checkAvailable() end



return m