--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.EventListenerAcceleration : cc.EventListener
local m = {}

--- 
---@param callback fun
---@return boolean
function m:init(callback) end

--- / Overrides
---@return cc.EventListenerAcceleration
function m:clone() end

--- 
---@return boolean
function m:checkAvailable() end

--- 
---@return cc.EventListenerAcceleration
function m:EventListenerAcceleration() end



return m