--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.EventListenerPhysicsContactWithBodies : cc.EventListenerPhysicsContact
local m = {}

--- 
---@param shapeA cc.PhysicsShape
---@param shapeB cc.PhysicsShape
---@return boolean
function m:hitTest(shapeA, shapeB) end

---  Create the listener. 
---@param bodyA cc.PhysicsBody
---@param bodyB cc.PhysicsBody
---@return cc.EventListenerPhysicsContactWithBodies
function m:create(bodyA, bodyB) end

--- 
---@return cc.EventListenerPhysicsContactWithBodies
function m:clone() end



return m