--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.EventListener : cc.Ref
local m = {}

---  Enables or disables the listener.<br>
--- note Only listeners with `enabled` state will be able to receive events.<br>
--- When an listener was initialized, it's enabled by default.<br>
--- An event listener can receive events when it is enabled and is not paused.<br>
--- paused state is always false when it is a fixed priority listener.<br>
--- param enabled True if enables the listener.
---@param enabled boolean
---@return cc.EventListener
function m:setEnabled(enabled) end

---  Checks whether the listener is enabled.<br>
--- return True if the listener is enabled.
---@return boolean
function m:isEnabled() end

---  Clones the listener, its subclasses have to override this method.
---@return cc.EventListener
function m:clone() end

---  Checks whether the listener is available.<br>
--- return True if the listener is available.
---@return boolean
function m:checkAvailable() end



return m