--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.EventListenerController : cc.EventListener
local m = {}

---  Create a controller event listener.<br>
--- return An autoreleased EventListenerController object.
---@return cc.EventListenerController
function m:create() end

--- 
---@return cc.EventListenerController
function m:clone() end

--- / Overrides
---@return boolean
function m:checkAvailable() end



return m