--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.EventCustom : cc.Event
local m = {}

---  Gets event name.<br>
--- return The name of the event.
---@return string
function m:getEventName() end

---  Constructor.<br>
--- param eventName A given name of the custom event.<br>
--- js ctor
---@param eventName string
---@return cc.EventCustom
function m:EventCustom(eventName) end



return m