--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.FadeOut : cc.FadeTo
local m = {}

--- js NA
---@param ac cc.FadeTo
---@return cc.FadeOut
function m:setReverseAction(ac) end

--- Creates the action.<br>
--- param d Duration time, in seconds.
---@param d float
---@return cc.FadeOut
function m:create(d) end

--- 
---@param target cc.Node
---@return cc.FadeOut
function m:startWithTarget(target) end

--- 
---@return cc.FadeOut
function m:clone() end

--- 
---@return cc.FadeTo
function m:reverse() end

--- 
---@return cc.FadeOut
function m:FadeOut() end



return m