--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.FadeOutUpTiles : cc.FadeOutTRTiles
local m = {}

--- brief Create the action with the grid size and the duration.<br>
--- param duration Specify the duration of the FadeOutUpTiles action. It's a value in seconds.<br>
--- param gridSize Specify the size of the grid.<br>
--- return If the creation success, return a pointer of FadeOutUpTiles action; otherwise, return nil.
---@param duration float
---@param gridSize cc.size
---@return cc.FadeOutUpTiles
function m:create(duration, gridSize) end

--- 
---@return cc.FadeOutUpTiles
function m:clone() end

--- 
---@param pos cc.vec2
---@param distance float
---@return cc.FadeOutUpTiles
function m:transformTile(pos, distance) end

--- 
---@param pos cc.size
---@param time float
---@return float
function m:testFunc(pos, time) end

--- 
---@return cc.FadeOutUpTiles
function m:FadeOutUpTiles() end



return m