--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.FadeOutBLTiles : cc.FadeOutTRTiles
local m = {}

--- brief Create the action with the grid size and the duration.<br>
--- param duration Specify the duration of the FadeOutBLTiles action. It's a value in seconds.<br>
--- param gridSize Specify the size of the grid.<br>
--- return If the creation success, return a pointer of FadeOutBLTiles action; otherwise, return nil.
---@param duration float
---@param gridSize cc.size
---@return cc.FadeOutBLTiles
function m:create(duration, gridSize) end

--- 
---@return cc.FadeOutBLTiles
function m:clone() end

--- 
---@param pos cc.size
---@param time float
---@return float
function m:testFunc(pos, time) end

--- 
---@return cc.FadeOutBLTiles
function m:FadeOutBLTiles() end



return m