--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.FadeTo : cc.ActionInterval
local m = {}

--- initializes the action with duration and opacity <br>
--- param duration in seconds
---@param duration float
---@param opacity uchar
---@return boolean
function m:initWithDuration(duration, opacity) end

--- Creates an action with duration and opacity.<br>
--- param duration Duration time, in seconds.<br>
--- param opacity A certain opacity, the range is from 0 to 255.<br>
--- return An autoreleased FadeTo object.
---@param duration float
---@param opacity uchar
---@return cc.FadeTo
function m:create(duration, opacity) end

--- 
---@param target cc.Node
---@return cc.FadeTo
function m:startWithTarget(target) end

--- 
---@return cc.FadeTo
function m:clone() end

--- 
---@return cc.FadeTo
function m:reverse() end

--- param time In seconds.
---@param time float
---@return cc.FadeTo
function m:update(time) end

--- 
---@return cc.FadeTo
function m:FadeTo() end



return m