--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.FiniteTimeAction : cc.Action
local m = {}

---  Set duration in seconds of the action. <br>
--- param duration In seconds of the action.
---@param duration float
---@return cc.FiniteTimeAction
function m:setDuration(duration) end

---  Get duration in seconds of the action. <br>
--- return The duration in seconds of the action.
---@return float
function m:getDuration() end

--- 
---@return cc.FiniteTimeAction
function m:clone() end

--- 
---@return cc.FiniteTimeAction
function m:reverse() end



return m