--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.FlipY : cc.ActionInstant
local m = {}

---  init the action 
---@param y boolean
---@return boolean
function m:initWithFlipY(y) end

---  Create the action.<br>
--- param y Flips the sprite vertically if true.<br>
--- return An autoreleased FlipY object.
---@param y boolean
---@return cc.FlipY
function m:create(y) end

--- 
---@return cc.FlipY
function m:clone() end

--- param time In seconds.
---@param time float
---@return cc.FlipY
function m:update(time) end

--- 
---@return cc.FlipY
function m:reverse() end

--- 
---@return cc.FlipY
function m:FlipY() end



return m