--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.FlipX3D : cc.Grid3DAction
local m = {}

--- brief Initializes an action with duration and grid size.<br>
--- param gridSize Specify the grid size of the FlipX3D action.<br>
--- param duration Specify the duration of the FlipX3D action. It's a value in seconds.<br>
--- return If the initialization success, return true; otherwise, return false.
---@param gridSize cc.size
---@param duration float
---@return boolean
function m:initWithSize(gridSize, duration) end

--- brief Initializes an action with duration.<br>
--- param duration Specify the duration of the FlipX3D action. It's a value in seconds.<br>
--- return If the initialization success, return true; otherwise, return false.
---@param duration float
---@return boolean
function m:initWithDuration(duration) end

--- brief Create the action with duration.<br>
--- param duration Specify the duration of the FilpX3D action. It's a value in seconds.<br>
--- return If the creation success, return a pointer of FilpX3D action; otherwise, return nil.
---@param duration float
---@return cc.FlipX3D
function m:create(duration) end

--- 
---@return cc.FlipX3D
function m:clone() end

--- 
---@param time float
---@return cc.FlipX3D
function m:update(time) end

--- 
---@return cc.FlipX3D
function m:FlipX3D() end



return m