--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.GridAction : cc.ActionInterval
local m = {}

--- brief Get the pointer of GridBase.<br>
--- return The pointer of GridBase.
---@return cc.GridBase
function m:getGrid() end

--- brief Initializes the action with size and duration.<br>
--- param duration The duration of the GridAction. It's a value in seconds.<br>
--- param gridSize The size of the GridAction should be.<br>
--- return Return true when the initialization success, otherwise return false.
---@param duration float
---@param gridSize cc.size
---@return boolean
function m:initWithDuration(duration, gridSize) end

--- 
---@param target cc.Node
---@return cc.GridAction
function m:startWithTarget(target) end

--- 
---@return cc.GridAction
function m:clone() end

--- 
---@return cc.GridAction
function m:reverse() end



return m