--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.Grid3DAction : cc.GridAction
local m = {}

--- brief Get the effect grid rect.<br>
--- return Return the effect grid rect.
---@return cc.rect
function m:getGridRect() end

--- 
---@return cc.Grid3DAction
function m:clone() end

--- 
---@return cc.GridBase
function m:getGrid() end



return m