--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class ccs.GUIReader : ccs.Ref
local m = {}

--- 
---@param strFilePath string
---@return ccs.GUIReader
function m:setFilePath(strFilePath) end

--- 
---@param fileName char
---@return ccui.Widget
function m:widgetFromJsonFile(fileName) end

--- 
---@return string
function m:getFilePath() end

--- 
---@param fileName char
---@return ccui.Widget
function m:widgetFromBinaryFile(fileName) end

--- 
---@param str char
---@return int
function m:getVersionInteger(str) end

--- 
---@return ccs.GUIReader
function m:destroyInstance() end

--- 
---@return ccs.GUIReader
function m:getInstance() end



return m