--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class ccui.HBox : ccui.Layout
local m = {}

--- 
---@param size cc.size
---@return boolean
function m:initWithSize(size) end

---@overload fun(self:ccui.HBox):ccui.HBox
---@param size cc.size
---@return ccui.HBox
function m:create(size) end

--- 
---@return boolean
function m:init() end

--- Default constructor<br>
--- js ctor<br>
--- lua new
---@return ccui.HBox
function m:HBox() end



return m