--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class ccui.ImageView : ccui.Widget,ccui.BlendProtocol
local m = {}

--- Returns the blending function that is currently being used.<br>
--- return A BlendFunc structure with source and destination factor which specified pixel arithmetic.<br>
--- js NA<br>
--- lua NA
---@return cc.BlendFunc
function m:getBlendFunc() end

--- Load texture for imageview.<br>
--- param fileName   file name of texture.<br>
---@param fileName string
---@param texType int
---@return ccui.ImageView
function m:loadTexture(fileName, texType) end

--- Sets the source blending function.<br>
--- param blendFunc A structure with source and destination factor to specify pixel arithmetic. e.g. {GL_ONE, GL_ONE}, {GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA}.<br>
--- js NA<br>
--- lua NA
---@param blendFunc cc.BlendFunc
---@return ccui.ImageView
function m:setBlendFunc(blendFunc) end

--- 
---@param imageFileName string
---@param texType int
---@return boolean
function m:init(imageFileName, texType) end

--- Enable scale9 renderer.<br>
--- param enabled Set to true will use scale9 renderer, false otherwise.
---@param enabled boolean
---@return ccui.ImageView
function m:setScale9Enabled(enabled) end

--- Updates the texture rect of the ImageView in points.<br>
--- It will call setTextureRect:rotated:untrimmedSize with rotated = NO, and utrimmedSize = rect.size.
---@param rect cc.rect
---@return ccui.ImageView
function m:setTextureRect(rect) end

--- Sets capInsets for imageview.<br>
--- The capInsets affects the ImageView's renderer only if `setScale9Enabled(true)` is called.<br>
--- param capInsets    capinsets for imageview
---@param capInsets cc.rect
---@return ccui.ImageView
function m:setCapInsets(capInsets) end

--- 
---@return cc.ResourceData
function m:getRenderFile() end

--- Get ImageView's capInsets size.<br>
--- return Query capInsets size in Rect<br>
--- see `setCapInsets(const Rect&)`
---@return cc.rect
function m:getCapInsets() end

--- Query whether button is using scale9 renderer or not.<br>
--- return whether button use scale9 renderer or not.
---@return boolean
function m:isScale9Enabled() end

---@overload fun(self:ccui.ImageView):ccui.ImageView
---@param imageFileName string
---@param texType int
---@return ccui.ImageView
function m:create(imageFileName, texType) end

--- 
---@return cc.Ref
function m:createInstance() end

--- 
---@return cc.Node
function m:getVirtualRenderer() end

--- 
---@param ignore boolean
---@return ccui.ImageView
function m:ignoreContentAdaptWithSize(ignore) end

--- 
---@return string
function m:getDescription() end

--- 
---@return boolean
function m:init() end

--- 
---@param glProgram cc.GLProgram
---@return ccui.ImageView
function m:setGLProgram(glProgram) end

--- 
---@param glProgramState cc.GLProgramState
---@return ccui.ImageView
function m:setGLProgramState(glProgramState) end

--- 
---@return cc.size
function m:getVirtualRendererSize() end

--- Default constructor<br>
--- js ctor<br>
--- lua new
---@return ccui.ImageView
function m:ImageView() end



return m