--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class ccui.LayoutParameter : ccui.Ref
local m = {}

--- Create a copy of original LayoutParameter.<br>
--- return A LayoutParameter pointer.
---@return ccui.LayoutParameter
function m:clone() end

--- Gets LayoutParameterType of LayoutParameter.<br>
--- see LayoutParameterType.<br>
--- return LayoutParameterType
---@return int
function m:getLayoutType() end

--- Create a cloned instance of LayoutParameter.<br>
--- return A LayoutParameter pointer.
---@return ccui.LayoutParameter
function m:createCloneInstance() end

--- Copy all the member field from argument LayoutParameter to self.<br>
--- param model A LayoutParameter instance.
---@param model ccui.LayoutParameter
---@return ccui.LayoutParameter
function m:copyProperties(model) end

--- Create a empty LayoutParameter.<br>
--- return A autorelease LayoutParameter instance.
---@return ccui.LayoutParameter
function m:create() end

--- Default constructor.<br>
--- lua new
---@return ccui.LayoutParameter
function m:LayoutParameter() end



return m