--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.MenuItemImage : cc.MenuItemSprite
local m = {}

---  Sets the sprite frame for the disabled image. 
---@param frame cc.SpriteFrame
---@return cc.MenuItemImage
function m:setDisabledSpriteFrame(frame) end

---  Sets the sprite frame for the selected image. 
---@param frame cc.SpriteFrame
---@return cc.MenuItemImage
function m:setSelectedSpriteFrame(frame) end

---  Sets the sprite frame for the normal image. 
---@param frame cc.SpriteFrame
---@return cc.MenuItemImage
function m:setNormalSpriteFrame(frame) end

--- 
---@return boolean
function m:init() end

---  Initializes a menu item with a normal, selected and disabled image with a callable object. 
---@param normalImage string
---@param selectedImage string
---@param disabledImage string
---@param callback fun
---@return boolean
function m:initWithNormalImage(normalImage, selectedImage, disabledImage, callback) end

--- js ctor
---@return cc.MenuItemImage
function m:MenuItemImage() end



return m