--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class ccs.MovementData : ccs.Ref
local m = {}

--- 
---@param boneName string
---@return ccs.MovementBoneData
function m:getMovementBoneData(boneName) end

--- 
---@param movBoneData ccs.MovementBoneData
---@return ccs.MovementData
function m:addMovementBoneData(movBoneData) end

--- 
---@return ccs.MovementData
function m:create() end

--- js ctor
---@return ccs.MovementData
function m:MovementData() end



return m