--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class ccs.MovementBoneData : ccs.Ref
local m = {}

--- 
---@return boolean
function m:init() end

--- 
---@param index int
---@return ccs.FrameData
function m:getFrameData(index) end

--- 
---@param frameData ccs.FrameData
---@return ccs.MovementBoneData
function m:addFrameData(frameData) end

--- 
---@return ccs.MovementBoneData
function m:create() end

--- js ctor
---@return ccs.MovementBoneData
function m:MovementBoneData() end



return m