--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.MoveTo : cc.MoveBy
local m = {}

---@overload fun(self:cc.MoveTo, duration:float, position:cc.vec3):boolean
---@param duration float
---@param position cc.vec2
---@return boolean
function m:initWithDuration(duration, position) end

---@overload fun(self:cc.MoveTo, duration:float, position:cc.vec3):cc.MoveTo
---@param duration float
---@param position cc.vec2
---@return cc.MoveTo
function m:create(duration, position) end

--- 
---@param target cc.Node
---@return cc.MoveTo
function m:startWithTarget(target) end

--- 
---@return cc.MoveTo
function m:clone() end

--- 
---@return cc.MoveTo
function m:reverse() end

--- 
---@return cc.MoveTo
function m:MoveTo() end



return m