--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.OrbitCamera : cc.ActionCamera
local m = {}

---  Initializes a OrbitCamera action with radius, delta-radius,  z, deltaZ, x, deltaX. 
---@param t float
---@param radius float
---@param deltaRadius float
---@param angleZ float
---@param deltaAngleZ float
---@param angleX float
---@param deltaAngleX float
---@return boolean
function m:initWithDuration(t, radius, deltaRadius, angleZ, deltaAngleZ, angleX, deltaAngleX) end

---  Creates a OrbitCamera action with radius, delta-radius,  z, deltaZ, x, deltaX. <br>
--- param t Duration in seconds.<br>
--- param radius The start radius.<br>
--- param deltaRadius The delta radius.<br>
--- param angleZ The start angle in Z.<br>
--- param deltaAngleZ The delta angle in Z.<br>
--- param angleX The start angle in X.<br>
--- param deltaAngleX The delta angle in X.<br>
--- return An OrbitCamera.
---@param t float
---@param radius float
---@param deltaRadius float
---@param angleZ float
---@param deltaAngleZ float
---@param angleX float
---@param deltaAngleX float
---@return cc.OrbitCamera
function m:create(t, radius, deltaRadius, angleZ, deltaAngleZ, angleX, deltaAngleX) end

--- 
---@param target cc.Node
---@return cc.OrbitCamera
function m:startWithTarget(target) end

--- 
---@return cc.OrbitCamera
function m:clone() end

--- 
---@param time float
---@return cc.OrbitCamera
function m:update(time) end

--- js ctor
---@return cc.OrbitCamera
function m:OrbitCamera() end



return m