--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.PageTurn3D : cc.Grid3DAction
local m = {}

--- brief Create an action with duration, grid size.<br>
--- param duration Specify the duration of the PageTurn3D action. It's a value in seconds.<br>
--- param gridSize Specify the size of the grid.<br>
--- return If the creation success, return a pointer of PageTurn3D action; otherwise, return nil.
---@param duration float
---@param gridSize cc.size
---@return cc.PageTurn3D
function m:create(duration, gridSize) end

--- 
---@return cc.PageTurn3D
function m:clone() end

--- js NA 
---@return cc.GridBase
function m:getGrid() end

--- 
---@param time float
---@return cc.PageTurn3D
function m:update(time) end



return m