--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.ParticleExplosion : cc.ParticleSystemQuad
local m = {}

--- 
---@return boolean
function m:init() end

--- 
---@param numberOfParticles int
---@return boolean
function m:initWithTotalParticles(numberOfParticles) end

---  Create a explosion particle system.<br>
--- return An autoreleased ParticleExplosion object.
---@return cc.ParticleExplosion
function m:create() end

---  Create a explosion particle system withe a fixed number of particles.<br>
--- param numberOfParticles A given number of particles.<br>
--- return An autoreleased ParticleExplosion object.<br>
--- js NA
---@param numberOfParticles int
---@return cc.ParticleExplosion
function m:createWithTotalParticles(numberOfParticles) end

--- js ctor
---@return cc.ParticleExplosion
function m:ParticleExplosion() end



return m