--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.ParticleGalaxy : cc.ParticleSystemQuad
local m = {}

--- 
---@return boolean
function m:init() end

--- 
---@param numberOfParticles int
---@return boolean
function m:initWithTotalParticles(numberOfParticles) end

---  Create a galaxy particle system.<br>
--- return An autoreleased ParticleGalaxy object.
---@return cc.ParticleGalaxy
function m:create() end

---  Create a galaxy particle system withe a fixed number of particles.<br>
--- param numberOfParticles A given number of particles.<br>
--- return An autoreleased ParticleGalaxy object.<br>
--- js NA
---@param numberOfParticles int
---@return cc.ParticleGalaxy
function m:createWithTotalParticles(numberOfParticles) end

--- js ctor
---@return cc.ParticleGalaxy
function m:ParticleGalaxy() end



return m