--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.ParticleFireworks : cc.ParticleSystemQuad
local m = {}

--- 
---@return boolean
function m:init() end

--- 
---@param numberOfParticles int
---@return boolean
function m:initWithTotalParticles(numberOfParticles) end

---  Create a fireworks particle system.<br>
--- return An autoreleased ParticleFireworks object.
---@return cc.ParticleFireworks
function m:create() end

---  Create a fireworks particle system withe a fixed number of particles.<br>
--- param numberOfParticles A given number of particles.<br>
--- return An autoreleased ParticleFireworks object.<br>
--- js NA
---@param numberOfParticles int
---@return cc.ParticleFireworks
function m:createWithTotalParticles(numberOfParticles) end

--- js ctor
---@return cc.ParticleFireworks
function m:ParticleFireworks() end



return m