--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.PhysicsJointFixed : cc.PhysicsJoint
local m = {}

--- 
---@return boolean
function m:createConstraints() end

---  Create a fixed joint.<br>
--- param a A is the body to connect.<br>
--- param b B is the body to connect.<br>
--- param anchr It's the pivot position.<br>
--- return A object pointer.
---@param a cc.PhysicsBody
---@param b cc.PhysicsBody
---@param anchr cc.vec2
---@return cc.PhysicsJointFixed
function m:construct(a, b, anchr) end



return m