--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.PhysicsJointRotaryLimit : cc.PhysicsJoint
local m = {}

---  Get the max rotation limit.
---@return float
function m:getMax() end

--- 
---@return boolean
function m:createConstraints() end

---  Set the min rotation limit.
---@param min float
---@return cc.PhysicsJointRotaryLimit
function m:setMin(min) end

---  Set the max rotation limit.
---@param max float
---@return cc.PhysicsJointRotaryLimit
function m:setMax(max) end

---  Get the min rotation limit.
---@return float
function m:getMin() end

---@overload fun(self:cc.PhysicsJointRotaryLimit, a:cc.PhysicsBody, b:cc.PhysicsBody):cc.PhysicsJointRotaryLimit
---@param a cc.PhysicsBody
---@param b cc.PhysicsBody
---@param min float
---@param max float
---@return cc.PhysicsJointRotaryLimit
function m:construct(a, b, min, max) end



return m