--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.PhysicsShapePolygon : cc.PhysicsShape
local m = {}

--- Get this polygon's points array count.<br>
--- return An integer number.
---@return int
function m:getPointsCount() end

--- Get a point of this polygon's points array.<br>
--- param i A index of this polygon's points array.<br>
--- return A point value.
---@param i int
---@return cc.vec2
function m:getPoint(i) end

--- Calculate the moment for a polygon.<br>
--- return A float number.
---@return float
function m:calculateDefaultMoment() end

--- Get this polygon's center position.<br>
--- return A Vec2 object.
---@return cc.vec2
function m:getCenter() end



return m