--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.PhysicsBody : cc.Component
local m = {}

---  Whether this physics body is affected by the physics world's gravitational force. 
---@return boolean
function m:isGravityEnabled() end

--- reset all the force applied to body. 
---@return cc.PhysicsBody
function m:resetForces() end

---  get the max of velocity 
---@return float
function m:getVelocityLimit() end

--- Set the group of body.<br>
--- Collision groups let you specify an integral group index. You can have all fixtures with the same group index always collide (positive index) or never collide (negative index).<br>
--- It have high priority than bit masks.
---@param group int
---@return cc.PhysicsBody
function m:setGroup(group) end

---  Get the body mass. 
---@return float
function m:getMass() end

--- Return bitmask of first shape.<br>
--- return If there is no shape in body, return default value.(0xFFFFFFFF)
---@return int
function m:getCollisionBitmask() end

---  set the body rotation offset 
---@return float
function m:getRotationOffset() end

---  get the body rotation. 
---@return float
function m:getRotation() end

---  Get the body moment of inertia. 
---@return float
function m:getMoment() end

--- Applies a immediate force to body.<br>
--- param impulse The impulse is applies to this body.<br>
--- param offset A Vec2 object, it is the offset from the body's center of gravity in world coordinates.
---@param impulse cc.vec2
---@param offset cc.vec2
---@return cc.PhysicsBody
function m:applyImpulse(impulse, offset) end

---  set body rotation offset, it's the rotation witch relative to node 
---@param rotation float
---@return cc.PhysicsBody
function m:setRotationOffset(rotation) end

--- Applies a continuous force to body.<br>
--- param force The force is applies to this body.<br>
--- param offset A Vec2 object, it is the offset from the body's center of gravity in world coordinates.
---@param force cc.vec2
---@param offset cc.vec2
---@return cc.PhysicsBody
function m:applyForce(force, offset) end

--- brief Add a shape to body.<br>
--- param shape The shape to be added.<br>
--- param addMassAndMoment If this is true, the shape's mass and moment will be added to body. The default is true.<br>
--- return This shape's pointer if added success or nullptr if failed.
---@param shape cc.PhysicsShape
---@param addMassAndMoment boolean
---@return cc.PhysicsShape
function m:addShape(shape, addMassAndMoment) end

--- Applies a torque force to body.<br>
--- param torque The torque is applies to this body.
---@param torque float
---@return cc.PhysicsBody
function m:applyTorque(torque) end

---  get the max of angular velocity 
---@return float
function m:getAngularVelocityLimit() end

---  set the max of angular velocity 
---@param limit float
---@return cc.PhysicsBody
function m:setAngularVelocityLimit(limit) end

---  Get the velocity of a body. 
---@return cc.vec2
function m:getVelocity() end

---  get linear damping. 
---@return float
function m:getLinearDamping() end

--- Remove all shapes.<br>
--- param reduceMassAndMoment If this is true, the body mass and moment will be reduced by shape. The default is true.
---@return cc.PhysicsBody
function m:removeAllShapes() end

--- Set angular damping.<br>
--- It is used to simulate fluid or air friction forces on the body.<br>
--- param damping The value is 0.0f to 1.0f.
---@param damping float
---@return cc.PhysicsBody
function m:setAngularDamping(damping) end

---  set the max of velocity 
---@param limit float
---@return cc.PhysicsBody
function m:setVelocityLimit(limit) end

---  set body to rest 
---@param rest boolean
---@return cc.PhysicsBody
function m:setResting(rest) end

---  get body position offset. 
---@return cc.vec2
function m:getPositionOffset() end

--- A mask that defines which categories this physics body belongs to.<br>
--- Every physics body in a scene can be assigned to up to 32 different categories, each corresponding to a bit in the bit mask. You define the mask values used in your game. In conjunction with the collisionBitMask and contactTestBitMask properties, you define which physics bodies interact with each other and when your game is notified of these interactions.<br>
--- param bitmask An integer number, the default value is 0xFFFFFFFF (all bits set).
---@param bitmask int
---@return cc.PhysicsBody
function m:setCategoryBitmask(bitmask) end

---  get the world body added to. 
---@return cc.PhysicsWorld
function m:getWorld() end

---  get the angular velocity of a body 
---@return float
function m:getAngularVelocity() end

---  get the body position. 
---@return cc.vec2
function m:getPosition() end

---  Set the body is affected by the physics world's gravitational force or not. 
---@param enable boolean
---@return cc.PhysicsBody
function m:setGravityEnable(enable) end

--- Return group of first shape.<br>
--- return If there is no shape in body, return default value.(0) 
---@return int
function m:getGroup() end

--- brief Set the body moment of inertia.<br>
--- note If you need add/subtract moment to body, don't use setMoment(getMoment() +/- moment), because the moment of body may be equal to PHYSICS_INFINITY, it will cause some unexpected result, please use addMoment() instead.
---@param moment float
---@return cc.PhysicsBody
function m:setMoment(moment) end

---  Get the body's tag. 
---@return int
function m:getTag() end

---  Convert the local point to world. 
---@param point cc.vec2
---@return cc.vec2
function m:local2World(point) end

--- Return bitmask of first shape.<br>
--- return If there is no shape in body, return default value.(0xFFFFFFFF)
---@return int
function m:getCategoryBitmask() end

--- brief Set dynamic to body.<br>
--- A dynamic body will effect with gravity.
---@param dynamic boolean
---@return cc.PhysicsBody
function m:setDynamic(dynamic) end

--- Get the first shape of the body shapes.<br>
--- return The first shape in this body.
---@return cc.PhysicsShape
function m:getFirstShape() end

--- Get the body shapes.<br>
--- return A Vector<PhysicsShape*> object contains PhysicsShape pointer.
---@return any[]
function m:getShapes() end

--- Return bitmask of first shape.<br>
--- return If there is no shape in body, return default value.(0x00000000)
---@return int
function m:getContactTestBitmask() end

--- Set the angular velocity of a body.<br>
--- param velocity The angular velocity is set to this body.
---@param velocity float
---@return cc.PhysicsBody
function m:setAngularVelocity(velocity) end

---  Convert the world point to local. 
---@param point cc.vec2
---@return cc.vec2
function m:world2Local(point) end

---@overload fun(self:cc.PhysicsBody, shape:int, reduceMassAndMoment:boolean):cc.PhysicsBody
---@param shape cc.PhysicsShape
---@param reduceMassAndMoment boolean
---@return cc.PhysicsBody
function m:removeShape(shape, reduceMassAndMoment) end

--- brief Set the body mass.<br>
--- attention If you need add/subtract mass to body, don't use setMass(getMass() +/- mass), because the mass of body may be equal to PHYSICS_INFINITY, it will cause some unexpected result, please use addMass() instead.
---@param mass float
---@return cc.PhysicsBody
function m:setMass(mass) end

--- brief Add moment of inertia to body.<br>
--- param moment If _moment(moment of the body) == PHYSICS_INFINITY, it remains.<br>
--- if moment == PHYSICS_INFINITY, _moment will be PHYSICS_INFINITY.<br>
--- if moment == -PHYSICS_INFINITY, _moment will not change.<br>
--- if moment + _moment <= 0, _moment will equal to MASS_DEFAULT(1.0)<br>
--- other wise, moment = moment + _moment;
---@param moment float
---@return cc.PhysicsBody
function m:addMoment(moment) end

--- Set the velocity of a body.<br>
--- param velocity The velocity is set to this body.
---@param velocity cc.vec2
---@return cc.PhysicsBody
function m:setVelocity(velocity) end

--- Set linear damping.<br>
--- it is used to simulate fluid or air friction forces on the body.<br>
--- param damping The value is 0.0f to 1.0f.
---@param damping float
---@return cc.PhysicsBody
function m:setLinearDamping(damping) end

--- A mask that defines which categories of physics bodies can collide with this physics body.<br>
--- When two physics bodies contact each other, a collision may occur. This body's collision mask is compared to the other body's category mask by performing a logical AND operation. If the result is a non-zero value, then this body is affected by the collision. Each body independently chooses whether it wants to be affected by the other body. For example, you might use this to avoid collision calculations that would make negligible changes to a body's velocity.<br>
--- param bitmask An integer number, the default value is 0xFFFFFFFF (all bits set).
---@param bitmask int
---@return cc.PhysicsBody
function m:setCollisionBitmask(bitmask) end

---  set body position offset, it's the position witch relative to node 
---@param position cc.vec2
---@return cc.PhysicsBody
function m:setPositionOffset(position) end

---  Set the body is allow rotation or not 
---@param enable boolean
---@return cc.PhysicsBody
function m:setRotationEnable(enable) end

---  Whether the body can rotation. 
---@return boolean
function m:isRotationEnabled() end

---  Get the rigid body of chipmunk. 
---@return cpBody
function m:getCPBody() end

---  Get angular damping. 
---@return float
function m:getAngularDamping() end

---  Get the angular velocity of a body at a local point.
---@param point cc.vec2
---@return cc.vec2
function m:getVelocityAtLocalPoint(point) end

---  Whether the body is at rest. 
---@return boolean
function m:isResting() end

--- brief Add mass to body.<br>
--- param mass If _mass(mass of the body) == PHYSICS_INFINITY, it remains.<br>
--- if mass == PHYSICS_INFINITY, _mass will be PHYSICS_INFINITY.<br>
--- if mass == -PHYSICS_INFINITY, _mass will not change.<br>
--- if mass + _mass <= 0, _mass will equal to MASS_DEFAULT(1.0)<br>
--- other wise, mass = mass + _mass;
---@param mass float
---@return cc.PhysicsBody
function m:addMass(mass) end

--- get the shape of the body.<br>
--- param   tag   An integer number that identifies a PhysicsShape object.<br>
--- return A PhysicsShape object pointer or nullptr if no shapes were found.
---@param tag int
---@return cc.PhysicsShape
function m:getShape(tag) end

---  set the body's tag. 
---@param tag int
---@return cc.PhysicsBody
function m:setTag(tag) end

---  get the angular velocity of a body at a world point 
---@param point cc.vec2
---@return cc.vec2
function m:getVelocityAtWorldPoint(point) end

--- A mask that defines which categories of bodies cause intersection notifications with this physics body.<br>
--- When two bodies share the same space, each body's category mask is tested against the other body's contact mask by performing a logical AND operation. If either comparison results in a non-zero value, an PhysicsContact object is created and passed to the physics world’s delegate. For best performance, only set bits in the contacts mask for interactions you are interested in.<br>
--- param bitmask An integer number, the default value is 0x00000000 (all bits cleared).
---@param bitmask int
---@return cc.PhysicsBody
function m:setContactTestBitmask(bitmask) end

---  remove the body from the world it added to 
---@return cc.PhysicsBody
function m:removeFromWorld() end

--- brief Test the body is dynamic or not.<br>
--- A dynamic body will effect with gravity.
---@return boolean
function m:isDynamic() end

---  get the node the body set to. 
---@return cc.Node
function m:getNode() end

--- Create a body contains a box shape.<br>
--- param   size Size contains this box's width and height.<br>
--- param   material A PhysicsMaterial object, the default value is PHYSICSSHAPE_MATERIAL_DEFAULT.<br>
--- param   offset A Vec2 object, it is the offset from the body's center of gravity in body local coordinates.<br>
--- return  An autoreleased PhysicsBody object pointer.
---@param size cc.size
---@param material cc.PhysicsMaterial
---@param offset cc.vec2
---@return cc.PhysicsBody
function m:createBox(size, material, offset) end

--- Create a body contains a EdgeSegment shape.<br>
--- param   a It's the edge's begin position.<br>
--- param   b It's the edge's end position.<br>
--- param   material A PhysicsMaterial object, the default value is PHYSICSSHAPE_MATERIAL_DEFAULT.<br>
--- param   border It's a edge's border width.<br>
--- return  An autoreleased PhysicsBody object pointer.
---@param a cc.vec2
---@param b cc.vec2
---@param material cc.PhysicsMaterial
---@param border float
---@return cc.PhysicsBody
function m:createEdgeSegment(a, b, material, border) end

---@overload fun(self:cc.PhysicsBody, mass:float):cc.PhysicsBody
---@overload fun(self:cc.PhysicsBody):cc.PhysicsBody
---@param mass float
---@param moment float
---@return cc.PhysicsBody
function m:create(mass, moment) end

--- Create a body contains a EdgeBox shape.<br>
--- param   size Size contains this box's width and height.<br>
--- param   material A PhysicsMaterial object, the default value is PHYSICSSHAPE_MATERIAL_DEFAULT.<br>
--- param   border It's a edge's border width.<br>
--- param   offset A Vec2 object, it is the offset from the body's center of gravity in body local coordinates.<br>
--- return  An autoreleased PhysicsBody object pointer.
---@param size cc.size
---@param material cc.PhysicsMaterial
---@param border float
---@param offset cc.vec2
---@return cc.PhysicsBody
function m:createEdgeBox(size, material, border, offset) end

--- Create a body contains a circle.<br>
--- param   radius A float number, it is the circle's radius.<br>
--- param   material A PhysicsMaterial object, the default value is PHYSICSSHAPE_MATERIAL_DEFAULT.<br>
--- param   offset A Vec2 object, it is the offset from the body's center of gravity in body local coordinates.<br>
--- return  An autoreleased PhysicsBody object pointer.
---@param radius float
---@param material cc.PhysicsMaterial
---@param offset cc.vec2
---@return cc.PhysicsBody
function m:createCircle(radius, material, offset) end

--- Set the enable value.<br>
--- If the body it isn't enabled, it will not has simulation by world.
---@param enable boolean
---@return cc.PhysicsBody
function m:setEnabled(enable) end

--- 
---@return cc.PhysicsBody
function m:onRemove() end

--- 
---@return cc.PhysicsBody
function m:onEnter() end

--- 
---@return cc.PhysicsBody
function m:onExit() end

--- 
---@return cc.PhysicsBody
function m:onAdd() end



return m