--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.PhysicsContactPreSolve
local m = {}

---  Get friction between two bodies.
---@return float
function m:getFriction() end

---  Get restitution between two bodies.
---@return float
function m:getRestitution() end

---  Set the friction.
---@param friction float
---@return cc.PhysicsContactPreSolve
function m:setFriction(friction) end

---  Ignore the rest of the contact presolve and postsolve callbacks. 
---@return cc.PhysicsContactPreSolve
function m:ignore() end

---  Get surface velocity between two bodies.
---@return cc.vec2
function m:getSurfaceVelocity() end

---  Set the surface velocity.
---@param velocity cc.vec2
---@return cc.PhysicsContactPreSolve
function m:setSurfaceVelocity(velocity) end

---  Set the restitution.
---@param restitution float
---@return cc.PhysicsContactPreSolve
function m:setRestitution(restitution) end



return m