--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.PhysicsSprite3D : cc.Sprite3D
local m = {}

---  synchronize node transformation to physics. 
---@return cc.PhysicsSprite3D
function m:syncNodeToPhysics() end

---  synchronize physics transformation to node. 
---@return cc.PhysicsSprite3D
function m:syncPhysicsToNode() end

---  Get the Physics3DObject. 
---@return cc.Physics3DObject
function m:getPhysicsObj() end

---  Set synchronization flag, see Physics3DComponent. 
---@param syncFlag int
---@return cc.PhysicsSprite3D
function m:setSyncFlag(syncFlag) end

--- 
---@return cc.PhysicsSprite3D
function m:PhysicsSprite3D() end



return m