--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.PhysicsShapeEdgePolygon : cc.PhysicsShape
local m = {}

--- Get this polygon's points array count.<br>
--- return An integer number.
---@return int
function m:getPointsCount() end

--- Get this polygon's center position.<br>
--- return A Vec2 object.
---@return cc.vec2
function m:getCenter() end



return m