--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.PhysicsJointRatchet : cc.PhysicsJoint
local m = {}

---  Get the ratchet angle.
---@return float
function m:getAngle() end

---  Set the ratchet angle.
---@param angle float
---@return cc.PhysicsJointRatchet
function m:setAngle(angle) end

--- 
---@return boolean
function m:createConstraints() end

---  Set the initial offset.
---@param phase float
---@return cc.PhysicsJointRatchet
function m:setPhase(phase) end

---  Get the initial offset.
---@return float
function m:getPhase() end

---  Set the distance between "clicks".
---@param ratchet float
---@return cc.PhysicsJointRatchet
function m:setRatchet(ratchet) end

---  Get the distance between "clicks".
---@return float
function m:getRatchet() end

---  Create a ratchet joint.<br>
--- param a A is the body to connect.<br>
--- param b B is the body to connect.<br>
--- param phase Phase is the initial offset to use when deciding where the ratchet angles are.<br>
--- param ratchet Ratchet is the distance between "clicks".<br>
--- return A object pointer.
---@param a cc.PhysicsBody
---@param b cc.PhysicsBody
---@param phase float
---@param ratchet float
---@return cc.PhysicsJointRatchet
function m:construct(a, b, phase, ratchet) end



return m