--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.PhysicsJointDistance : cc.PhysicsJoint
local m = {}

--- 
---@return boolean
function m:createConstraints() end

---  Set the distance of the anchor points.
---@param distance float
---@return cc.PhysicsJointDistance
function m:setDistance(distance) end

---  Get the distance of the anchor points.
---@return float
function m:getDistance() end

---  Create a fixed distance joint.<br>
--- param a A is the body to connect.<br>
--- param b B is the body to connect.<br>
--- param anchr1 Anchr1 is the anchor point on body a.<br>
--- param anchr2 Anchr2 is the anchor point on body b.<br>
--- return A object pointer.
---@param a cc.PhysicsBody
---@param b cc.PhysicsBody
---@param anchr1 cc.vec2
---@param anchr2 cc.vec2
---@return cc.PhysicsJointDistance
function m:construct(a, b, anchr1, anchr2) end



return m