--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.Physics3DObject : cc.Ref
local m = {}

---  Set the user data. 
---@param userData void
---@return cc.Physics3DObject
function m:setUserData(userData) end

---  Get the user data. 
---@return void
function m:getUserData() end

---  Get the Physics3DObject Type. 
---@return int
function m:getObjType() end

---  Internal method. Set the pointer of Physics3DWorld. 
---@param world cc.Physics3DWorld
---@return cc.Physics3DObject
function m:setPhysicsWorld(world) end

---  Get the world matrix of Physics3DObject. 
---@return mat4_table
function m:getWorldTransform() end

---  Get the pointer of Physics3DWorld. 
---@return cc.Physics3DWorld
function m:getPhysicsWorld() end

---  Set the mask of Physics3DObject. 
---@param mask uint
---@return cc.Physics3DObject
function m:setMask(mask) end

---  Get the collision callback function. 
---@return fun
function m:getCollisionCallback() end

---  Get the mask of Physics3DObject. 
---@return uint
function m:getMask() end

---  Check has collision callback function. 
---@return boolean
function m:needCollisionCallback() end



return m