--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.PolygonInfo
local m = {}

--- 
---@return string
function m:getFilename() end

--- get sum of all triangle area size<br>
--- return sum of all triangle area size
---@return float
function m:getArea() end

--- 
---@return cc.rect
function m:getRect() end

--- 
---@param filename string
---@return cc.PolygonInfo
function m:setFilename(filename) end

--- set the data to be a pointer to a number of Quads<br>
--- the member verts will not be released when this PolygonInfo destructs<br>
--- as the verts memory are managed by other objects<br>
--- param quad  a pointer to the V3F_C4B_T2F_Quad quads
---@param quads cc.V3F_C4B_T2F_Quad
---@param numberOfQuads int
---@return cc.PolygonInfo
function m:setQuads(quads, numberOfQuads) end

--- get vertex count<br>
--- return number of vertices
---@return uint
function m:getVertCount() end

--- get triangles count<br>
--- return number of triangles
---@return uint
function m:getTrianglesCount() end

--- set the data to be a pointer to a quad<br>
--- the member verts will not be released when this PolygonInfo destructs<br>
--- as the verts memory are managed by other objects<br>
--- param quad  a pointer to the V3F_C4B_T2F_Quad object
---@param quad cc.V3F_C4B_T2F_Quad
---@return cc.PolygonInfo
function m:setQuad(quad) end

--- set the data to be a pointer to a triangles<br>
--- the member verts will not be released when this PolygonInfo destructs<br>
--- as the verts memory are managed by other objects<br>
--- param triangles  a pointer to the TrianglesCommand::Triangles object
---@param triangles cc.TrianglesCommand::Triangles
---@return cc.PolygonInfo
function m:setTriangles(triangles) end

--- 
---@param rect cc.rect
---@return cc.PolygonInfo
function m:setRect(rect) end

--- Creates an empty Polygon info<br>
--- memberof PolygonInfo<br>
--- return PolygonInfo object
---@return cc.PolygonInfo
function m:PolygonInfo() end



return m