--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.ProgressFromTo : cc.ActionInterval
local m = {}

--- brief Initializes the action with a duration, a "from" percentage and a "to" percentage.<br>
--- param duration Specify the duration of the ProgressFromTo action. It's a value in seconds.<br>
--- param fromPercentage Specify the source percentage.<br>
--- param toPercentage Specify the destination percentage.<br>
--- return If the creation success, return true; otherwise, return false.
---@param duration float
---@param fromPercentage float
---@param toPercentage float
---@return boolean
function m:initWithDuration(duration, fromPercentage, toPercentage) end

--- brief Create and initializes the action with a duration, a "from" percentage and a "to" percentage.<br>
--- param duration Specify the duration of the ProgressFromTo action. It's a value in seconds.<br>
--- param fromPercentage Specify the source percentage.<br>
--- param toPercentage Specify the destination percentage.<br>
--- return If the creation success, return a pointer of ProgressFromTo action; otherwise, return nil.
---@param duration float
---@param fromPercentage float
---@param toPercentage float
---@return cc.ProgressFromTo
function m:create(duration, fromPercentage, toPercentage) end

--- 
---@param target cc.Node
---@return cc.ProgressFromTo
function m:startWithTarget(target) end

--- 
---@return cc.ProgressFromTo
function m:clone() end

--- 
---@return cc.ProgressFromTo
function m:reverse() end

--- 
---@param time float
---@return cc.ProgressFromTo
function m:update(time) end

--- 
---@return cc.ProgressFromTo
function m:ProgressFromTo() end



return m