--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class ccui.RadioButton : ccui.AbstractCheckButton
local m = {}

--- Add a callback function which would be called when radio button is selected or unselected.<br>
---@param callback fun
---@return ccui.RadioButton
function m:addEventListener(callback) end

---@overload fun(self:ccui.RadioButton):ccui.RadioButton
---@overload fun(self:ccui.RadioButton, backGround:string, backGroundSelected:string, cross:int):ccui.RadioButton
---@param backGround string
---@param backGroundSelected string
---@param cross string
---@param backGroundDisabled string
---@param frontCrossDisabled string
---@param texType int
---@return ccui.RadioButton
function m:create(backGround, backGroundSelected, cross, backGroundDisabled, frontCrossDisabled, texType) end

--- 
---@return cc.Ref
function m:createInstance() end

--- 
---@return string
function m:getDescription() end

--- Default constructor.<br>
--- lua new
---@return ccui.RadioButton
function m:RadioButton() end



return m