--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.RenderState : cc.Ref
local m = {}

---  Texture that will use in the CC_Texture0 uniform.<br>
--- Added to be backwards compatible. Use Samplers from .material instead.
---@param texture cc.Texture2D
---@return cc.RenderState
function m:setTexture(texture) end

--- Returns the topmost RenderState in the hierarchy below the given RenderState.
---@param below cc.RenderState
---@return cc.RenderState
function m:getTopmost(below) end

---  Returns the texture that is going to be used for CC_Texture0.<br>
--- Added to be backwards compatible.
---@return cc.Texture2D
function m:getTexture() end

--- Binds the render state for this RenderState and any of its parents, top-down,<br>
--- for the given pass.
---@param pass cc.Pass
---@return cc.RenderState
function m:bind(pass) end

--- 
---@return string
function m:getName() end

--- 
---@return cc.RenderState::StateBlock
function m:getStateBlock() end

--- 
---@param parent cc.RenderState
---@return cc.RenderState
function m:setParent(parent) end

--- Static initializer that is called during game startup.
---@return cc.RenderState
function m:initialize() end



return m