--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.Repeat : cc.ActionInterval
local m = {}

---  Sets the inner action.<br>
--- param action The inner action.
---@param action cc.FiniteTimeAction
---@return cc.Repeat
function m:setInnerAction(action) end

---  initializes a Repeat action. Times is an unsigned integer between 1 and pow(2,30) 
---@param pAction cc.FiniteTimeAction
---@param times uint
---@return boolean
function m:initWithAction(pAction, times) end

---  Gets the inner action.<br>
--- return The inner action.
---@return cc.FiniteTimeAction
function m:getInnerAction() end

---  Creates a Repeat action. Times is an unsigned integer between 1 and pow(2,30).<br>
--- param action The action needs to repeat.<br>
--- param times The repeat times.<br>
--- return An autoreleased Repeat object.
---@param action cc.FiniteTimeAction
---@param times uint
---@return cc.Repeat
function m:create(action, times) end

--- 
---@param target cc.Node
---@return cc.Repeat
function m:startWithTarget(target) end

--- 
---@return cc.Repeat
function m:reverse() end

--- 
---@return cc.Repeat
function m:clone() end

--- 
---@return cc.Repeat
function m:stop() end

--- param dt In seconds.
---@param dt float
---@return cc.Repeat
function m:update(dt) end

--- 
---@return boolean
function m:isDone() end

--- 
---@return cc.Repeat
function m:Repeat() end



return m