--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.RepeatForever : cc.ActionInterval
local m = {}

---  Sets the inner action.<br>
--- param action The inner action.
---@param action cc.ActionInterval
---@return cc.RepeatForever
function m:setInnerAction(action) end

---  initializes the action 
---@param action cc.ActionInterval
---@return boolean
function m:initWithAction(action) end

---  Gets the inner action.<br>
--- return The inner action.
---@return cc.ActionInterval
function m:getInnerAction() end

---  Creates the action.<br>
--- param action The action need to repeat forever.<br>
--- return An autoreleased RepeatForever object.
---@param action cc.ActionInterval
---@return cc.RepeatForever
function m:create(action) end

--- 
---@param target cc.Node
---@return cc.RepeatForever
function m:startWithTarget(target) end

--- 
---@return cc.RepeatForever
function m:clone() end

--- 
---@return boolean
function m:isDone() end

--- 
---@return cc.RepeatForever
function m:reverse() end

--- param dt In seconds.
---@param dt float
---@return cc.RepeatForever
function m:step(dt) end

--- 
---@return cc.RepeatForever
function m:RepeatForever() end



return m