--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class ccui.RichElementNewLine : ccui.RichElement
local m = {}

--- brief Create a RichElementNewLine with various arguments.<br>
--- param tag A integer tag value.<br>
--- param color A color in Color3B.<br>
--- param opacity A opacity in GLubyte.<br>
--- return A RichElementNewLine instance.
---@param tag int
---@param color cc.c3b
---@param opacity uchar
---@return ccui.RichElementNewLine
function m:create(tag, color, opacity) end

--- brief Default constructor.<br>
--- js ctor<br>
--- lua new
---@return ccui.RichElementNewLine
function m:RichElementNewLine() end



return m