--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class ccui.RichElementCustomNode : ccui.RichElement
local m = {}

--- brief Initialize a RichElementCustomNode with various arguments.<br>
--- param tag A integer tag value.<br>
--- param color A color in Color3B.<br>
--- param opacity A opacity in GLubyte.<br>
--- param customNode A custom node pointer.<br>
--- return True if initialize success, false otherwise.
---@param tag int
---@param color cc.c3b
---@param opacity uchar
---@param customNode cc.Node
---@return boolean
function m:init(tag, color, opacity, customNode) end

--- brief Create a RichElementCustomNode with various arguments.<br>
--- param tag A integer tag value.<br>
--- param color A color in Color3B.<br>
--- param opacity A opacity in GLubyte.<br>
--- param customNode A custom node pointer.<br>
--- return A RichElementCustomNode instance.
---@param tag int
---@param color cc.c3b
---@param opacity uchar
---@param customNode cc.Node
---@return ccui.RichElementCustomNode
function m:create(tag, color, opacity, customNode) end

--- brief Default constructor.<br>
--- js ctor<br>
--- lua new
---@return ccui.RichElementCustomNode
function m:RichElementCustomNode() end



return m