--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.ScaleBy : cc.ScaleTo
local m = {}

---@overload fun(self:cc.ScaleBy, duration:float, sx:float, sy:float):cc.ScaleBy
---@overload fun(self:cc.ScaleBy, duration:float, sx:float):cc.ScaleBy
---@param duration float
---@param sx float
---@param sy float
---@param sz float
---@return cc.ScaleBy
function m:create(duration, sx, sy, sz) end

--- 
---@param target cc.Node
---@return cc.ScaleBy
function m:startWithTarget(target) end

--- 
---@return cc.ScaleBy
function m:clone() end

--- 
---@return cc.ScaleBy
function m:reverse() end

--- 
---@return cc.ScaleBy
function m:ScaleBy() end



return m