--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.Scene : cc.Node
local m = {}

--- 
---@return boolean
function m:initWithPhysics() end

--- 
---@return cc.Scene
function m:setCameraOrderDirty() end

---@overload fun(self:cc.Scene, renderer:cc.Renderer, eyeTransforms:mat4_table, eyeProjections:mat4_table):cc.Scene
---@param renderer cc.Renderer
---@param eyeTransforms mat4_table
---@param eyeProjections mat4_table
---@param multiViewCount uint
---@return cc.Scene
function m:render(renderer, eyeTransforms, eyeProjections, multiViewCount) end

--- 
---@param deltaTime float
---@return cc.Scene
function m:stepPhysicsAndNavigation(deltaTime) end

--- 
---@param event cc.EventCustom
---@return cc.Scene
function m:onProjectionChanged(event) end

---  Get the physics world of the scene.<br>
--- return The physics world of the scene.<br>
--- js NA
---@return cc.PhysicsWorld
function m:getPhysicsWorld() end

--- 
---@param size cc.size
---@return boolean
function m:initWithSize(size) end

---  Get the default camera.<br>
--- js NA<br>
--- return The default camera of scene.
---@return cc.Camera
function m:getDefaultCamera() end

---  Creates a new Scene object with a predefined Size. <br>
--- param size The predefined size of scene.<br>
--- return An autoreleased Scene object.<br>
--- js NA
---@param size cc.size
---@return cc.Scene
function m:createWithSize(size) end

---  Creates a new Scene object. <br>
--- return An autoreleased Scene object.
---@return cc.Scene
function m:create() end

---  Create a scene with physics.<br>
--- return An autoreleased Scene object with physics.<br>
--- js NA
---@return cc.Scene
function m:createWithPhysics() end

--- 
---@return boolean
function m:init() end

--- 
---@return string
function m:getDescription() end

---  override function 
---@return cc.Scene
function m:removeAllChildren() end

--- 
---@return cc.Scene
function m:Scene() end



return m