--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.Show : cc.ActionInstant
local m = {}

---  Allocates and initializes the action.<br>
--- return  An autoreleased Show object.
---@return cc.Show
function m:create() end

--- 
---@return cc.Show
function m:clone() end

--- param time In seconds.
---@param time float
---@return cc.Show
function m:update(time) end

--- 
---@return cc.ActionInstant
function m:reverse() end

--- 
---@return cc.Show
function m:Show() end



return m