--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class ccs.SkewFrame : ccs.Frame
local m = {}

--- 
---@return float
function m:getSkewY() end

--- 
---@param skewx float
---@return ccs.SkewFrame
function m:setSkewX(skewx) end

--- 
---@param skewy float
---@return ccs.SkewFrame
function m:setSkewY(skewy) end

--- 
---@return float
function m:getSkewX() end

--- 
---@return ccs.SkewFrame
function m:create() end

--- 
---@return ccs.Frame
function m:clone() end

--- 
---@return ccs.SkewFrame
function m:SkewFrame() end



return m