--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.SkewTo : cc.ActionInterval
local m = {}

--- param t In seconds.
---@param t float
---@param sx float
---@param sy float
---@return boolean
function m:initWithDuration(t, sx, sy) end

--- Creates the action.<br>
--- param t Duration time, in seconds.<br>
--- param sx Skew x angle.<br>
--- param sy Skew y angle.<br>
--- return An autoreleased SkewTo object.
---@param t float
---@param sx float
---@param sy float
---@return cc.SkewTo
function m:create(t, sx, sy) end

--- 
---@param target cc.Node
---@return cc.SkewTo
function m:startWithTarget(target) end

--- 
---@return cc.SkewTo
function m:clone() end

--- 
---@return cc.SkewTo
function m:reverse() end

--- param time In seconds.
---@param time float
---@return cc.SkewTo
function m:update(time) end

--- 
---@return cc.SkewTo
function m:SkewTo() end



return m