--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class ccs.Skin : ccs.Sprite
local m = {}

--- 
---@return ccs.Bone
function m:getBone() end

--- 
---@return mat4_table
function m:getNodeToWorldTransformAR() end

--- 
---@return string
function m:getDisplayName() end

--- 
---@return ccs.Skin
function m:updateArmatureTransform() end

--- 
---@param bone ccs.Bone
---@return ccs.Skin
function m:setBone(bone) end

---@overload fun(self:ccs.Skin):ccs.Skin
---@param pszFileName string
---@return ccs.Skin
function m:create(pszFileName) end

--- 
---@param pszSpriteFrameName string
---@return ccs.Skin
function m:createWithSpriteFrameName(pszSpriteFrameName) end

--- 
---@param renderer cc.Renderer
---@param transform mat4_table
---@param flags uint
---@return ccs.Skin
function m:draw(renderer, transform, flags) end

--- 
---@return mat4_table
function m:getNodeToWorldTransform() end

--- 
---@param spriteFrameName string
---@return boolean
function m:initWithSpriteFrameName(spriteFrameName) end

--- 
---@param filename string
---@return boolean
function m:initWithFile(filename) end

--- 
---@return ccs.Skin
function m:updateTransform() end

--- js ctor
---@return ccs.Skin
function m:Skin() end



return m