--------------------------------
-- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class sp
---@field SkeletonRenderer sp.SkeletonRenderer
---@field SkeletonAnimation sp.SkeletonAnimation


return nil