--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.Spawn : cc.ActionInterval
local m = {}

--- 
---@param arrayOfActions any[]
---@return boolean
function m:init(arrayOfActions) end

---  initializes the Spawn action with the 2 actions to spawn 
---@param action1 cc.FiniteTimeAction
---@param action2 cc.FiniteTimeAction
---@return boolean
function m:initWithTwoActions(action1, action2) end

--- 
---@param target cc.Node
---@return cc.Spawn
function m:startWithTarget(target) end

--- 
---@return cc.Spawn
function m:clone() end

--- 
---@return cc.Spawn
function m:stop() end

--- 
---@return cc.Spawn
function m:reverse() end

--- param time In seconds.
---@param time float
---@return cc.Spawn
function m:update(time) end

--- 
---@return cc.Spawn
function m:Spawn() end



return m