--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.Speed : cc.Action
local m = {}

---  Replace the interior action.<br>
--- param action The new action, it will replace the running action.
---@param action cc.ActionInterval
---@return cc.Speed
function m:setInnerAction(action) end

---  Return the speed.<br>
--- return The action speed.
---@return float
function m:getSpeed() end

---  Alter the speed of the inner function in runtime. <br>
--- param speed Alter the speed of the inner function in runtime.
---@param speed float
---@return cc.Speed
function m:setSpeed(speed) end

---  Initializes the action. 
---@param action cc.ActionInterval
---@param speed float
---@return boolean
function m:initWithAction(action, speed) end

---  Return the interior action.<br>
--- return The interior action.
---@return cc.ActionInterval
function m:getInnerAction() end

---  Create the action and set the speed.<br>
--- param action An action.<br>
--- param speed The action speed.
---@param action cc.ActionInterval
---@param speed float
---@return cc.Speed
function m:create(action, speed) end

--- 
---@param target cc.Node
---@return cc.Speed
function m:startWithTarget(target) end

--- 
---@return cc.Speed
function m:reverse() end

--- 
---@return cc.Speed
function m:clone() end

--- 
---@return cc.Speed
function m:stop() end

--- param dt in seconds.
---@param dt float
---@return cc.Speed
function m:step(dt) end

---  Return true if the action has finished.<br>
--- return Is true if the action has finished.
---@return boolean
function m:isDone() end

--- 
---@return cc.Speed
function m:Speed() end



return m