--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class ccs.SpriteDisplayData : ccs.DisplayData
local m = {}

--- 
---@param displayData ccs.DisplayData
---@return ccs.SpriteDisplayData
function m:copy(displayData) end

--- 
---@return ccs.SpriteDisplayData
function m:create() end

--- js ctor
---@return ccs.SpriteDisplayData
function m:SpriteDisplayData() end



return m