--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.TargetedAction : cc.ActionInterval
local m = {}

---@return cc.Node
function m:getForcedTarget() end

---  Init an action with the specified action and forced target 
---@param target cc.Node
---@param action cc.FiniteTimeAction
---@return boolean
function m:initWithTarget(target, action) end

---  Sets the target that the action will be forced to run with.<br>
--- param forcedTarget The target that the action will be forced to run with.
---@param forcedTarget cc.Node
---@return cc.TargetedAction
function m:setForcedTarget(forcedTarget) end

---  Create an action with the specified action and forced target.<br>
--- param target The target needs to override.<br>
--- param action The action needs to override.<br>
--- return An autoreleased TargetedAction object.
---@param target cc.Node
---@param action cc.FiniteTimeAction
---@return cc.TargetedAction
function m:create(target, action) end

--- 
---@param target cc.Node
---@return cc.TargetedAction
function m:startWithTarget(target) end

--- 
---@return cc.TargetedAction
function m:clone() end

--- 
---@return cc.TargetedAction
function m:stop() end

--- 
---@return cc.TargetedAction
function m:reverse() end

--- param time In seconds.
---@param time float
---@return cc.TargetedAction
function m:update(time) end

--- 
---@return cc.TargetedAction
function m:TargetedAction() end



return m