--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class ccs.TextureData : ccs.Ref
local m = {}

--- 
---@param index int
---@return ccs.ContourData
function m:getContourData(index) end

--- 
---@return boolean
function m:init() end

--- 
---@param contourData ccs.ContourData
---@return ccs.TextureData
function m:addContourData(contourData) end

--- 
---@return ccs.TextureData
function m:create() end

--- js ctor
---@return ccs.TextureData
function m:TextureData() end



return m