--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class ccui.TextBMFont : ccui.Widget
local m = {}

--- Gets the string length of the label.<br>
--- Note: This length will be larger than the raw string length,<br>
--- if you want to get the raw string length, you should call this->getString().size() instead<br>
--- return  string length.
---@return int
function m:getStringLength() end

--- 
---@return string
function m:getString() end

--- 
---@param value string
---@return ccui.TextBMFont
function m:setString(value) end

--- 
---@return cc.ResourceData
function m:getRenderFile() end

---  init a bitmap font atlas with an initial string and the FNT file 
---@param fileName string
---@return ccui.TextBMFont
function m:setFntFile(fileName) end

--- reset TextBMFont inner label
---@return ccui.TextBMFont
function m:resetRender() end

---@overload fun(self:ccui.TextBMFont):ccui.TextBMFont
---@param text string
---@param filename string
---@return ccui.TextBMFont
function m:create(text, filename) end

--- 
---@return cc.Ref
function m:createInstance() end

--- 
---@return cc.Node
function m:getVirtualRenderer() end

--- Returns the "class name" of widget.
---@return string
function m:getDescription() end

--- 
---@return cc.size
function m:getVirtualRendererSize() end

--- Default constructor<br>
--- js ctor<br>
--- lua new
---@return ccui.TextBMFont
function m:TextBMFont() end



return m