--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class ccs.Timeline : ccs.Ref
local m = {}

--- 
---@return ccs.Timeline
function m:clone() end

--- 
---@param frameIndex int
---@return ccs.Timeline
function m:gotoFrame(frameIndex) end

--- 
---@param node cc.Node
---@return ccs.Timeline
function m:setNode(node) end

--- 
---@return ccs.ActionTimeline
function m:getActionTimeline() end

--- 
---@param frame ccs.Frame
---@param index int
---@return ccs.Timeline
function m:insertFrame(frame, index) end

--- 
---@param tag int
---@return ccs.Timeline
function m:setActionTag(tag) end

--- 
---@param frame ccs.Frame
---@return ccs.Timeline
function m:addFrame(frame) end

--- 
---@return any[]
function m:getFrames() end

--- 
---@return int
function m:getActionTag() end

--- 
---@return cc.Node
function m:getNode() end

--- 
---@param frame ccs.Frame
---@return ccs.Timeline
function m:removeFrame(frame) end

--- 
---@param action ccs.ActionTimeline
---@return ccs.Timeline
function m:setActionTimeline(action) end

--- 
---@param frameIndex int
---@return ccs.Timeline
function m:stepToFrame(frameIndex) end

--- 
---@return ccs.Timeline
function m:create() end

--- 
---@return ccs.Timeline
function m:Timeline() end



return m