--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.Timer : cc.Ref
local m = {}

--- 
---@param seconds float
---@param repeat_ uint
---@param delay float
---@return cc.Timer
function m:setupTimerWithInterval(seconds, repeat_, delay) end

---  triggers the timer 
---@param dt float
---@return cc.Timer
function m:update(dt) end

--- 
---@return boolean
function m:isAborted() end

--- 
---@return boolean
function m:isExhausted() end

--- 
---@param dt float
---@return cc.Timer
function m:trigger(dt) end

--- 
---@return cc.Timer
function m:cancel() end

--- 
---@return cc.Timer
function m:setAborted() end



return m