--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.TintTo : cc.ActionInterval
local m = {}

---  initializes the action with duration and color 
---@param duration float
---@param red uchar
---@param green uchar
---@param blue uchar
---@return boolean
function m:initWithDuration(duration, red, green, blue) end

---@overload fun(self:cc.TintTo, duration:float, red:cc.c3b):cc.TintTo
---@param duration float
---@param red uchar
---@param green uchar
---@param blue uchar
---@return cc.TintTo
function m:create(duration, red, green, blue) end

--- 
---@param target cc.Node
---@return cc.TintTo
function m:startWithTarget(target) end

--- 
---@return cc.TintTo
function m:clone() end

--- 
---@return cc.TintTo
function m:reverse() end

--- param time In seconds.
---@param time float
---@return cc.TintTo
function m:update(time) end

--- 
---@return cc.TintTo
function m:TintTo() end



return m