--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.TintBy : cc.ActionInterval
local m = {}

---  initializes the action with duration and color 
---@param duration float
---@param deltaRed short
---@param deltaGreen short
---@param deltaBlue short
---@return boolean
function m:initWithDuration(duration, deltaRed, deltaGreen, deltaBlue) end

--- Creates an action with duration and color.<br>
--- param duration Duration time, in seconds.<br>
--- param deltaRed Delta red color.<br>
--- param deltaGreen Delta green color.<br>
--- param deltaBlue Delta blue color.<br>
--- return An autoreleased TintBy object.
---@param duration float
---@param deltaRed short
---@param deltaGreen short
---@param deltaBlue short
---@return cc.TintBy
function m:create(duration, deltaRed, deltaGreen, deltaBlue) end

--- 
---@param target cc.Node
---@return cc.TintBy
function m:startWithTarget(target) end

--- 
---@return cc.TintBy
function m:clone() end

--- 
---@return cc.TintBy
function m:reverse() end

--- param time In seconds.
---@param time float
---@return cc.TintBy
function m:update(time) end

--- 
---@return cc.TintBy
function m:TintBy() end



return m