--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.TMXObjectGroup : cc.Ref
local m = {}

---  Sets the offset position of child objects. <br>
--- param offset The offset position of child objects.
---@param offset cc.vec2
---@return cc.TMXObjectGroup
function m:setPositionOffset(offset) end

---  Return the value for the specific property name. <br>
--- param propertyName The specific property name.<br>
--- return Return the value for the specific property name.<br>
--- js NA
---@param propertyName string
---@return cc.Value
function m:getProperty(propertyName) end

---  Gets the offset position of child objects. <br>
--- return The offset position of child objects.
---@return cc.vec2
function m:getPositionOffset() end

---  Return the dictionary for the specific object name.<br>
--- It will return the 1st object found on the array for the given name.<br>
--- return Return the dictionary for the specific object name.
---@param objectName string
---@return table<any:any>
function m:getObject(objectName) end

---@return any[]
function m:getObjects() end

---  Set the group name. <br>
--- param groupName A string,it is used to set the group name.
---@param groupName string
---@return cc.TMXObjectGroup
function m:setGroupName(groupName) end

---@return table<any:any>
function m:getProperties() end

---  Get the group name. <br>
--- return The group name.
---@return string
function m:getGroupName() end

---  Sets the list of properties.<br>
--- param properties The list of properties.
---@param properties table<any:any>
---@return cc.TMXObjectGroup
function m:setProperties(properties) end

---  Sets the array of the objects.<br>
--- param objects The array of the objects.
---@param objects any[]
---@return cc.TMXObjectGroup
function m:setObjects(objects) end

--- js ctor
---@return cc.TMXObjectGroup
function m:TMXObjectGroup() end



return m