--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class ccexp.TMXTiledMap : ccexp.Node
local m = {}

---  Set object groups. <br>
--- param groups An object groups.
---@param groups any[]
---@return cc.experimental::TMXTiledMap
function m:setObjectGroups(groups) end

---  Return the value for the specific property name.<br>
--- return Return the value for the specific property name.
---@param propertyName string
---@return cc.Value
function m:getProperty(propertyName) end

---  Set the map's size property measured in tiles.<br>
--- param mapSize The map's size property measured in tiles.
---@param mapSize cc.size
---@return cc.experimental::TMXTiledMap
function m:setMapSize(mapSize) end

---  Return the TMXObjectGroup for the specific group. <br>
--- return Return the TMXObjectGroup for the specific group.
---@param groupName string
---@return cc.TMXObjectGroup
function m:getObjectGroup(groupName) end

---@return any[]
function m:getObjectGroups() end

---  The tiles's size property measured in pixels.<br>
--- return The tiles's size property measured in pixels.
---@return cc.size
function m:getTileSize() end

---  The map's size property measured in tiles. <br>
--- return The map's size property measured in tiles.
---@return cc.size
function m:getMapSize() end

---  Get properties.<br>
--- return Properties.
---@return table<any:any>
function m:getProperties() end

---  Return properties dictionary for tile GID.<br>
--- return Return properties dictionary for tile GID.
---@param GID int
---@return cc.Value
function m:getPropertiesForGID(GID) end

---  Set the tiles's size property measured in pixels. <br>
--- param tileSize The tiles's size property measured in pixels.
---@param tileSize cc.size
---@return cc.experimental::TMXTiledMap
function m:setTileSize(tileSize) end

---  Set properties. <br>
--- param properties An ValueMap Properties.
---@param properties table<any:any>
---@return cc.experimental::TMXTiledMap
function m:setProperties(properties) end

---  Return the FastTMXLayer for the specific layer. <br>
--- return Return the FastTMXLayer for the specific layer.
---@param layerName string
---@return cc.experimental::TMXLayer
function m:getLayer(layerName) end

---  Get map orientation. <br>
--- return The map orientation.
---@return int
function m:getMapOrientation() end

---  Set map orientation. <br>
--- param mapOrientation The map orientation.
---@param mapOrientation int
---@return cc.experimental::TMXTiledMap
function m:setMapOrientation(mapOrientation) end

---  Creates a TMX Tiled Map with a TMX file.<br>
--- return An autorelease object.
---@param tmxFile string
---@return cc.experimental::TMXTiledMap
function m:create(tmxFile) end

---  Initializes a TMX Tiled Map with a TMX formatted XML string and a path to TMX resources. <br>
--- param tmxString A TMX formatted XML string.<br>
--- param resourcePath A path to TMX resources.<br>
--- return An autorelease object.
---@param tmxString string
---@param resourcePath string
---@return cc.experimental::TMXTiledMap
function m:createWithXML(tmxString, resourcePath) end

--- 
---@return string
function m:getDescription() end



return m