--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.TMXTilesetInfo : cc.Ref
local m = {}

--- 
---@param gid uint
---@return cc.rect
function m:getRectForGID(gid) end

--- js ctor
---@return cc.TMXTilesetInfo
function m:TMXTilesetInfo() end



return m