--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.ToggleVisibility : cc.ActionInstant
local m = {}

---  Allocates and initializes the action.<br>
--- return An autoreleased ToggleVisibility object.
---@return cc.ToggleVisibility
function m:create() end

--- 
---@return cc.ToggleVisibility
function m:clone() end

--- param time In seconds.
---@param time float
---@return cc.ToggleVisibility
function m:update(time) end

--- 
---@return cc.ToggleVisibility
function m:reverse() end

--- 
---@return cc.ToggleVisibility
function m:ToggleVisibility() end



return m