--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.TransitionMoveInR : cc.TransitionMoveInL
local m = {}

---  Creates a transition with duration and incoming scene.<br>
--- param t Duration time, in seconds.<br>
--- param scene A given scene.<br>
--- return A autoreleased TransitionMoveInR object.
---@param t float
---@param scene cc.Scene
---@return cc.TransitionMoveInR
function m:create(t, scene) end

--- 
---@return cc.TransitionMoveInR
function m:TransitionMoveInR() end



return m