--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.TransitionTurnOffTiles : cc.TransitionScene,cc.TransitionEaseScene
local m = {}

--- 
---@param action cc.ActionInterval
---@return cc.ActionInterval
function m:easeActionWithAction(action) end

---  Creates a transition with duration and incoming scene.<br>
--- param t Duration time, in seconds.<br>
--- param scene A given scene.<br>
--- return A autoreleased TransitionTurnOffTiles object.
---@param t float
---@param scene cc.Scene
---@return cc.TransitionTurnOffTiles
function m:create(t, scene) end

--- js NA
---@param renderer cc.Renderer
---@param transform mat4_table
---@param flags uint
---@return cc.TransitionTurnOffTiles
function m:draw(renderer, transform, flags) end

--- 
---@return cc.TransitionTurnOffTiles
function m:TransitionTurnOffTiles() end



return m