--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.TransitionFadeTR : cc.TransitionScene,cc.TransitionEaseScene
local m = {}

--- 
---@param action cc.ActionInterval
---@return cc.ActionInterval
function m:easeActionWithAction(action) end

---  Returns the action that will be performed with size.<br>
--- param size A given size.<br>
--- return The action that will be performed.
---@param size cc.size
---@return cc.ActionInterval
function m:actionWithSize(size) end

---  Creates a transition with duration and incoming scene.<br>
--- param t Duration time, in seconds.<br>
--- param scene A given scene.<br>
--- return A autoreleased TransitionFadeTR object.
---@param t float
---@param scene cc.Scene
---@return cc.TransitionFadeTR
function m:create(t, scene) end

--- 
---@param renderer cc.Renderer
---@param transform mat4_table
---@param flags uint
---@return cc.TransitionFadeTR
function m:draw(renderer, transform, flags) end

--- 
---@return cc.TransitionFadeTR
function m:TransitionFadeTR() end



return m