--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.TransitionSceneOriented : cc.TransitionScene
local m = {}

---  initializes a transition with duration and incoming scene 
---@param t float
---@param scene cc.Scene
---@param orientation int
---@return boolean
function m:initWithDuration(t, scene, orientation) end

---  Creates a transition with duration, incoming scene and orientation.<br>
--- param t Duration time, in seconds.<br>
--- param scene A given scene.<br>
--- param orientation A given orientation: LeftOver, RightOver, UpOver, DownOver.<br>
--- return A autoreleased TransitionSceneOriented object.
---@param t float
---@param scene cc.Scene
---@param orientation int
---@return cc.TransitionSceneOriented
function m:create(t, scene, orientation) end

--- 
---@return cc.TransitionSceneOriented
function m:TransitionSceneOriented() end



return m