--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.TransitionScene : cc.Scene
local m = {}

--- 
---@return cc.Scene
function m:getInScene() end

---  Called after the transition finishes.
---@return cc.TransitionScene
function m:finish() end

---  initializes a transition with duration and incoming scene 
---@param t float
---@param scene cc.Scene
---@return boolean
function m:initWithDuration(t, scene) end

--- 
---@return float
function m:getDuration() end

---  Used by some transitions to hide the outer scene.
---@return cc.TransitionScene
function m:hideOutShowIn() end

---  Creates a base transition with duration and incoming scene.<br>
--- param t Duration time, in seconds.<br>
--- param scene A given scene.<br>
--- return A autoreleased TransitionScene object.
---@param t float
---@param scene cc.Scene
---@return cc.TransitionScene
function m:create(t, scene) end

--- 
---@param renderer cc.Renderer
---@param transform mat4_table
---@param flags uint
---@return cc.TransitionScene
function m:draw(renderer, transform, flags) end

--- 
---@return cc.TransitionScene
function m:cleanup() end

--- 
---@return cc.TransitionScene
function m:TransitionScene() end



return m