--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.TransitionSlideInL : cc.TransitionScene,cc.TransitionEaseScene
local m = {}

---  Returns the action that will be performed by the incoming and outgoing scene.<br>
--- return The action that will be performed by the incoming and outgoing scene.
---@return cc.ActionInterval
function m:action() end

--- 
---@param action cc.ActionInterval
---@return cc.ActionInterval
function m:easeActionWithAction(action) end

---  Creates a transition with duration and incoming scene.<br>
--- param t Duration time, in seconds.<br>
--- param scene A given scene.<br>
--- return A autoreleased TransitionSlideInL object.
---@param t float
---@param scene cc.Scene
---@return cc.TransitionSlideInL
function m:create(t, scene) end

--- 
---@return cc.TransitionSlideInL
function m:TransitionSlideInL() end



return m