--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.TransitionFlipAngular : cc.TransitionSceneOriented
local m = {}

---@overload fun(self:cc.TransitionFlipAngular, t:float, s:cc.Scene):cc.TransitionFlipAngular
---@param t float
---@param s cc.Scene
---@param o int
---@return cc.TransitionFlipAngular
function m:create(t, s, o) end

--- 
---@return cc.TransitionFlipAngular
function m:TransitionFlipAngular() end



return m