--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.TransitionRotoZoom : cc.TransitionScene
local m = {}

---  Creates a transition with duration and incoming scene.<br>
--- param t Duration time, in seconds.<br>
--- param scene A given scene.<br>
--- return A autoreleased TransitionRotoZoom object.
---@param t float
---@param scene cc.Scene
---@return cc.TransitionRotoZoom
function m:create(t, scene) end

--- 
---@return cc.TransitionRotoZoom
function m:TransitionRotoZoom() end



return m