--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.TransitionProgress : cc.TransitionScene
local m = {}

---  Creates a transition with duration and incoming scene.<br>
--- param t Duration time, in seconds.<br>
--- param scene A given scene.<br>
--- return An autoreleased TransitionProgress object.
---@param t float
---@param scene cc.Scene
---@return cc.TransitionProgress
function m:create(t, scene) end

--- 
---@return cc.TransitionProgress
function m:TransitionProgress() end



return m