--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.TransitionFlipY : cc.TransitionSceneOriented
local m = {}

---@overload fun(self:cc.TransitionFlipY, t:float, s:cc.Scene):cc.TransitionFlipY
---@param t float
---@param s cc.Scene
---@param o int
---@return cc.TransitionFlipY
function m:create(t, s, o) end

--- 
---@return cc.TransitionFlipY
function m:TransitionFlipY() end



return m