--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.TransitionProgressOutIn : cc.TransitionProgress
local m = {}

---  Creates a transition with duration and incoming scene.<br>
--- param t Duration time, in seconds.<br>
--- param scene A given scene.<br>
--- return An autoreleased TransitionProgressOutIn object.
---@param t float
---@param scene cc.Scene
---@return cc.TransitionProgressOutIn
function m:create(t, scene) end

--- js ctor
---@return cc.TransitionProgressOutIn
function m:TransitionProgressOutIn() end



return m