--------------------------------
--- generated by EmmyLua-Api-Cocos2dx-Generator
--------------------------------

---@class cc.TransitionJumpZoom : cc.TransitionScene
local m = {}

---  Creates a transition with duration and incoming scene.<br>
--- param t Duration time, in seconds.<br>
--- param scene A given scene.<br>
--- return A autoreleased TransitionJumpZoom object.
---@param t float
---@param scene cc.Scene
---@return cc.TransitionJumpZoom
function m:create(t, scene) end

--- 
---@return cc.TransitionJumpZoom
function m:TransitionJumpZoom() end



return m